### ISSUE TITLE
Platform Clarification

### ISSUE THREAD

**Issue by Fireflies** [iSach/UltraCosmetics#1]
>UltraCosmetics is a Spigot 1.8.8 plugin which adds cool cosmetics for hub servers.

Whilst Spigot is now considered the de-facto standard for running 1.8 servers, many end users still consider the CraftBukkit versions maintained by the Spigot team to _be_ Spigot. Adding clarification to the README could perhaps help prevent people from running into `ClassNotFoundException`s when loading classes relying on the chat component API that is not present in the standard CraftBukkit JAR.

A simple "You **must** be running Spigot, not CraftBukkit to use this plugin" warning should get the job done.

**Comment by iSach** [comment]
Oh okay! Thanks :) 
Yes may not be clear for some people ^^

Except that, would you know any licenses which could only allow private modifying. So people can't redistribute what I give, even if it's free, modified or not. And also can't be used for commercial uses.
Because I put a lot of time and I'd like to be protected from guys who steal code and use it to get $$$. 

Thanks in advance,
Sacha.

**Comment by Fireflies** [comment]
Have you looked at the Creative Commons licenses? Specifically the CC BY-NC-SA license. :)
http://creativecommons.org/licenses/by-nc-sa/4.0/

![License Graphic](http://i.imgur.com/f9oJzGn.png)

**Comment by iSach** [comment]
and it can apply to source code? I heard that CC was not good for a source code.

Yes but distribute for free? Like commercial use forbids distributing for money right?

Thanks!

**Comment by Fireflies** [comment]
It is advised you use other licenses, however there's no reason to not use a creative commons license, I'm using one on a project I'm working on infact and I feel like it'll be great :)

And yes, the no commercial use bit stops people reselling your hard work. :P

**Comment by Fireflies** [comment]
I'd also highly recommend reading [this](http://stackoverflow.com/questions/243196/what-is-the-difference-between-creative-commons-and-gpl-licensing)

**Comment by iSach** [comment]
Okay! Thanks a lot :smile:
