### ISSUE TITLE
Error on 1.8.9 Using Java 8

### ISSUE THREAD

**Issue by TheIntelloBox** [iSach/UltraCosmetics#101]
http://pastebin.com/GSnTAL88

**Comment by iSach** [comment]
Désolé pour le très long délai de réponse, le paste a expiré, as-tu encore l'erreur que tu avais avec la version 2.3.1 ?

**Comment by TheIntelloBox** [comment]
Non je ne l'ai plus. ;(

**Comment by iSach** [comment]
Merci d'ouvrrir une autre issue si ça arrive à nouveau

**Comment by TheIntelloBox** [comment]
Pas de soucis.
