### ISSUE TITLE
[QUESTION] Is here some kind of api?

### ISSUE THREAD

**Issue by supertassu** [iSach/UltraCosmetics#102]
So, is here some kind of api? Thanks.

**Comment by iSach** [comment]
Depends on what you'd like to do, adding cosmetics is not supported yet

**Comment by supertassu** [comment]
Just opening the gui for selecting cosmetics.

**Comment by iSach** [comment]
Here:
https://github.com/iSach/UltraCosmetics/tree/master/core/src/main/java/be/isach/ultracosmetics/manager

All these classes are the menus, they contain a static method for opening.

**Comment by supertassu** [comment]
Thank you.
