### ISSUE TITLE
EROR ()

### ISSUE THREAD

**Issue by FunnyCraft** [iSach/UltraCosmetics#107]
http://pastebin.com/nhZ5vwRt

**Comment by FunnyCraft** [comment]
http://pastebin.com/KHdNQEcF

**Comment by FunnyCraft** [comment]
You need to getServer().getPluginManager().registerEvents(LISTENER_CLASS, PLUGIN_CLASS);

In your case, registerEvents(this, this), since your listener class is the plugin class.

**Comment by FunnyCraft** [comment]
NEXT EROR http://pastebin.com/fh0pStM9

**Comment by iSach** [comment]
"You need to getServer().getPluginManager().registerEvents(LISTENER_CLASS, PLUGIN_CLASS);

In your case, registerEvents(this, this), since your listener class is the plugin class."

What are you talking about?

Error already know.

Last error is from NCP.

**Comment by FunnyCraft** [comment]
You need to register the event

**Comment by iSach** [comment]
it is registered, I know how to register events..
It is a NullPointerException.

**Comment by FunnyCraft** [comment]
Then what to do

**Comment by FunnyCraft** [comment]
http://pastebin.com/VszA0Mbg

**Comment by iSach** [comment]
Comes from NCP.

**Comment by FunnyCraft** [comment]
NO!

**Comment by supertassu** [comment]
@FunnyCraft it comes from NCP.

**Comment by iSach** [comment]
Either from NCP, either from Minecraft Server trying to limit.

**Comment by iSach** [comment]
From Paperspigot.
