### ISSUE TITLE
Pets instantly despawn after being spawned.

### ISSUE THREAD

**Issue by ataranlen** [iSach/UltraCosmetics#108]
Tested versions: 1.9.2, 1.9.4
Using Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Steps: 

- Load just UltraCosmetics 2.1.5
- Login as an OP with * permissions
- Open the pet menu
- click on 'Piggy'

Expected: a Piggy should spawn and follow me around until dismissed
Actual: a Piggy spawns, but instantly gets despawned.

Logs: http://pastebin.com/V6vZ5Dv3
Screenshot: http://i.imgur.com/LWWDWQq.png

**Comment by iSach** [comment]
Wow.
I think it's the first time I receive a complete issue.
Every time it's often "doeznt work plz help" without infos.
:p

I will have a look as soon as possible.

**Comment by ataranlen** [comment]
I try to provided detailed reports because that is what I would expect from users of my plugins and my players.

I'll be testing again on the latest builds of spigot 1.9.2 and 1.9.4 this afternoon. (probably will sneak in a test on 1.8.8 as well, since it wasn't working their either)

The worst part of all this, It seems to work fine two of my servers on 1.9.2, but not others, with ultracosmetics configured the same, and permissions the same. 

I tried to see about adding additional logging for the despawn cause, but I couldn't figure out how to compile the plugin with Gradle. (I'm used to Maven and straight up java compiling in Eclipse)

**Comment by iSach** [comment]
When a pet is spawned, a task is repeated each 2 ticks (or 1, not sure now) anyway this task checks some things and it can lead to an instant des pawn of the cosmetic. The most common cause is the world not being added in Enabled Worlds in config.

**Comment by ataranlen** [comment]
That would probably do it. The plugin config was copied from another server.

Shouldn't running the menu be blocked if the plugin isn't enabled on the world? Perhaps add a check and throw an error message?

**Comment by iSach** [comment]
Indeed it shouldn't allow menu to be opened 

Yes it is planned to add a message

**Comment by iSach** [comment]
Message added when world isn't enabled. (@see 2.3)

**Comment by ataranlen** [comment]
As an extension to this, in 1.10, the pumpling doesn't spawn anymore. It spawns an adult zombie, with no summon message or pumpkin.
