### ISSUE TITLE
No sounds in UltraCosmetics

### ISSUE THREAD

**Issue by aj4sure125** [iSach/UltraCosmetics#111]
Heya.

So for some reason lately, sounds have stopped working in UltraCosmetics all together. Is this possibly due to ViaVersion? I have ViaVersion on my server which has versions supporting 1.9 - 1.9.4. Is this due to a sound glitch based off the previous issue I had?

Also, here's a video about it: https://youtu.be/Vr3TQp8FKMQ

Thanks.

**Comment by iSach** [comment]
It's almost sure it's due to via version.

**Comment by aj4sure125** [comment]
It's actually due to 1.9.4. Sounds work on 1.9.2, but not 1.9.4

**Comment by aj4sure125** [comment]
Yea 1.9.4 has an issue with sounds. Anyway to fix them? Thanks

**Comment by iSach** [comment]
Fixed in 2.3.1
