### ISSUE TITLE
Gadget ammo treasure chest probability

### ISSUE THREAD

**Issue by OneTQ** [iSach/UltraCosmetics#113]
Is it possible to change the probability of receiving ammo for a certain gadget. Also, is it possible to make the amount of ammo received in the treasure chest less or more for specific gadgets. If so, how? If not, I think the feature should be implemented.

**Comment by iSach** [comment]
Not yet, currently, only category. I'm not adding it because when I add a gadget people will have to recalculate for every gadget etc. Maybe later.
