### ISSUE TITLE
Disable collisions for pets

### ISSUE THREAD

**Issue by ataranlen** [iSach/UltraCosmetics#115]
We had an issue where a pet pushed a player off a ledge in the nether. Can you add an option to disable collisions with players for pets?

**Comment by iSach** [comment]
I don't know how to do that, but I'll search.

**Comment by iSach** [comment]
Planned and added to TO-DO list.

**Comment by ataranlen** [comment]
Shouldn't you leave the issue open if you're planning to fix it?

**Comment by iSach** [comment]
it's noted on another list, I don't think it's needed to have aswell Github issue open.
