### ISSUE TITLE
Pet's armor stand can disconnect.

### ISSUE THREAD

**Issue by ataranlen** [iSach/UltraCosmetics#116]
We've got another issue with the armor stand disconnecting from the pet.

http://imgur.com/hki6aOD

Steps to Reproduce:
Summon a pet wolf (Also tested with a bunny)
Move around

Expected: 
The pet's armor stand will follow the pet

Actual:
The pet's armor stand is on the ground, and does not follow the pet.

**Comment by ataranlen** [comment]
In addition, the pet's armor stand with the name does not despawn when the pet is despawned, such as on logout.

**Comment by iSach** [comment]
Seems to be caused by water.
I already tried to fix, but can't do anything there is a strange behaviour in water of armorstands.

**Comment by ataranlen** [comment]
It doesn't seem to only happen in water, I have seen it happen on a flat surface, with no water in sight

**Comment by ataranlen** [comment]
But occurring to the player that reported it to me, it got much better in a the last version, and we are on 1.10 now.

**Comment by iSach** [comment]
Great, open a new issue if you're having issues again.
