### ISSUE TITLE
error 1.10

### ISSUE THREAD

**Issue by mat41997** [iSach/UltraCosmetics#117]
logs
http://hastebin.com/uvuqazetoh.avrasm

timings
https://timings.aikar.co/v2/?id=673b6d2c39f04613baec03813bb1eab7

**Comment by 112madgamer** [comment]
That is because it does not support 1.10 there is a open pull request that hopefully will be merged soon that adds some support for 1.10

**Comment by iSach** [comment]
@112madgamer It does support 1.10. I couldn't merge because the merge has been opened and I had to modify things before accepting it, but it broke the compatibility, so I manually added 1.10 support.
It has been tested and is working with 1.10

@mat41997 Try 2.2.1

**Comment by 112madgamer** [comment]
When i posted that it did not support it
