### ISSUE TITLE
Error spammed in console

### ISSUE THREAD

**Issue by DragonbornCommunity** [iSach/UltraCosmetics#118]
- Error: http://pastebin.com/6qRsWyrk
- UltraCosmetics v2.2 
- running CraftBukkit version git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

The error is spammed every second in console. Please fix.

**Comment by iSach** [comment]
Are you still having the issue in 2.3.1?

**Comment by DragonbornCommunity** [comment]
Solved in latest version.
