### ISSUE TITLE
Despawned Spider

### ISSUE THREAD

**Issue by CraftaPanda** [iSach/UltraCosmetics#119]
Hi, once I spawn a spider mount it automatically despawns

**Comment by 112madgamer** [comment]
Please when you report errors WE NEED OF INFO 

What version of the plugin are you running? 
What version is the plugin?
Is there a error in the log if so then post it.

**Comment by iSach** [comment]
- It can be Enabled-Worlds, where your world isn't added to the list in config.
- Or you're not allowing monsters to spawn there (WorldGuard etc), and as Spider is a UltraCosmetics custom entity, it can't bypass WorldGuard.
