### ISSUE TITLE
error 2 - 1.10

### ISSUE THREAD

**Issue by mat41997** [iSach/UltraCosmetics#121]
logs
http://pastebin.com/zb2rsqYY

timings
https://timings.aikar.co/v2/?id=8464b300cf3945a2ab2005ae130560af

**Comment by iSach** [comment]
Comes from Paperspigot

**Comment by mat41997** [comment]
yes

**Comment by iSach** [comment]
I can't do anything about it, it just denies to exceed a certain velocity, take a look at paperspigot config maybe
