### ISSUE TITLE
Holograms wont go away

### ISSUE THREAD

**Issue by kemit-the-frog** [iSach/UltraCosmetics#124]
Hello, 
On my server, a player was opening a treasure chest and the server crashed, so the holograms are still there i have taken this plugin off. reset its data, took holographic displays off and took its data off and it keeps staying.

How can I get rid if these pesky holograms? is there a data base for the holograms? Or do i need to give up on it?

**Comment by daani142** [comment]
try: /killall nametag or /killall nametags

**Comment by kemit-the-frog** [comment]
Nope that does not work

**Comment by iSach** [comment]
/minecraft:kill @e[type=ArmorStand,r=5]
When being near the hologram

**Comment by kemit-the-frog** [comment]
Thank you so much! That worked
