### ISSUE TITLE
Nyan Sheep 

### ISSUE THREAD

**Issue by GoNotCougsWA** [iSach/UltraCosmetics#125]
@iSach In a old version I will hear a Nyan Cat Song using note blocks when I use the Nyan Sheep, But when I use the Nyan Sheep I do not hear it. The Old version will have a songs folder that had all the songs in the plugin folder but I do not see it the song folder. Should this be working?

Plugin Version: 2.3.2
Bukkit Version: 1.8.8

ERROR:
There is no error

**Comment by daani142** [comment]
Do you have Noteblockapi?

**Comment by daani142** [comment]
I have the same problem: version: 2.3.2 and spigot 1.9.2

**Comment by DynamicThijs** [comment]
Yup it does not work on 1.9 and 1.10
Please fix it iSach ;)

**Comment by JustMaffie** [comment]
Thats kinda weird

**Comment by GoNotCougsWA** [comment]
Maybe he forgot to add it when he updated to 1.10

**Comment by GoNotCougsWA** [comment]
@iSach

**Comment by iSach** [comment]
Due to now about 7 hours trying to fix the bug, NoteBlockAPI support is removed from UltraCosmetics.
