### ISSUE TITLE
Could not pass event VehicleExitEvent to UltraCosmetics v2.3.2

### ISSUE THREAD

**Issue by TheChampTF** [iSach/UltraCosmetics#127]
http://paste.yu8.me/?26268d869d8f3a86#R92HC12K8AnUUSPMdj9QsRme3osYke7oMKDWTFdq3i8=

**Comment by aycgit** [comment]
issue is fixed in version 2.3.3
u can close this issue now

**Comment by TheChampTF** [comment]
Super, thanks!
