### ISSUE TITLE
Emote glitching and pet names

### ISSUE THREAD

**Issue by daani142** [iSach/UltraCosmetics#128]
Dear iSach,

Sorry for my repost but this time I will add more information:

CONSOLE:
===============================================================================================================================================
24.06 06:26:05 [Server] [Informatie] UltraCosmetics ->
24.06 06:26:05 [Server] [Informatie] UltraCosmetics -> Registering commands...
24.06 06:26:05 [Server] [Informatie] UltraCosmetics -> Registered subcommand 'gadgets'
24.06 06:26:05 [Server] [Informatie] UltraCosmetics -> Registered subcommand 'selfview'
24.06 06:26:05 [Server] [Informatie] UltraCosmetics -> Registered subcommand 'menu'
24.06 06:26:05 [Server] [Informatie] UltraCosmetics -> Registered subcommand 'give'
24.06 06:26:05 [Server] [Informatie] UltraCosmetics -> Registered subcommand 'toggle'
24.06 06:26:05 [Server] [Informatie] UltraCosmetics -> Registered subcommand 'clear'
24.06 06:26:05 [Server] [Informatie] UltraCosmetics -> Registered subcommand 'treasure'
24.06 06:26:05 [Server] [Informatie] UltraCosmetics -> Registered command: '/ultracosmetics'.
24.06 06:26:05 [Server] [Informatie] UltraCosmetics -> Registered command: '/uc'.
24.06 06:26:05 [Server] [Informatie] UltraCosmetics -> Registered commands.
24.06 06:26:05 [Server] [Informatie] UltraCosmetics ->
24.06 06:26:06 [Server] Skipped 1 lines due to rate limit (30/s)
24.06 06:26:06 [Server] [Informatie] UltraCosmetics -> Cosmetics Registered.
24.06 06:26:06 [Server] [Informatie] UltraCosmetics ->
24.06 06:26:06 [Server] [Informatie] UltraCosmetics -> Registering listeners...
24.06 06:26:06 [Server] [Informatie] UltraCosmetics -> Listeners registered.
24.06 06:26:06 [Server] [Informatie] UltraCosmetics ->
24.06 06:26:06 [Server] [Informatie] UltraCosmetics ->
24.06 06:26:06 [Server] [Informatie] UltraCosmetics -> UltraCosmetics successfully finished loading and is now enabled! (server: 1.9 -> 1.9.2)
24.06 06:26:06 [Server] [Informatie] UltraCosmetics -> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
================================================================================================================================================
Errors: no errors so far I can see :D
Version: Ultra Cosmetics 2.3.2
Server: Spigot 1.9.2

Problem:
- Pet names will not follow correctly above heads:
![picture 1](https://cloud.githubusercontent.com/assets/20072631/16330027/b6502742-39e6-11e6-99f5-6ec1369e98ad.png)
![picture 2](https://cloud.githubusercontent.com/assets/20072631/16330041/d7951f3e-39e6-11e6-85ec-c91c14e0392a.png)

(Here you can see it in gif picture: https://gyazo.com/38d48a684fa3033374854bbf493c6574)

- If you select an Emote from the emotes menu. And after that you select an helmet from the suits menu. You will get the selected emote in you hand and on your head it will switch from selecting helmet to emoticon. > https://gyazo.com/b7a7dd837387bff2a9d1d872dc1ba1d9 

Plugins that I use:
- Advanced portals
- Animated Frames
- AntiRS
- Armorstandtools
- Auto-airdrop
- Automessage
- Chest commands
- Citizens
- CommandNPC
- Custom join items
- Essentials
- Groupmanager
- Holograms
- KingKits
- Libdisguises
- Mapmanager
- Mediamenu
- Menubuilder
- multiverse core
- multiverse inventory
- Murder
- Npclib
- Nicknamer
- NoteblockAPI
- PacketListenerAPI
- PlaceholderAPI
- Playerheads
- proreports
- recourcepackapi
- scoreboardstats
- spawntp
- ultracosmetics < your plugin :+1: 
- Vault
- Voidworld
- World edit
- World guard

I hope you can help me with this!

**Comment by TheChampTF** [comment]
Can confirm the names over the pets is badly glitched and don’t follow the given pet at all.

In regards to the emote they work part time.
