### ISSUE TITLE
Few suggestions & bugs

### ISSUE THREAD

**Issue by TheChampTF** [iSach/UltraCosmetics#130]
First of, thanks for making this plugin!

Pets section:
- Name over the pets is glitchy
- Wither is offensiv towards all (make him friendly)
- Pumpling (crash server) + it is a Zombie (Should it not be a floating pumpkin?) (make him friendly)
* See more [here](https://github.com/iSach/UltraCosmetics/issues/129)
- Elf, just drops playerheads at you (No presents)

Gadgets:
- Freeze Cannon is to OP (Could be used for xray + don’t work under/on water)
* Suggest changed to packed ice.
- Trampoline is having issues with de spawn and it don’t stay for 75s

Mounts:
- None of the horses can ride in water
* At least give the water horse an option to could cross with out despawn
- Dragon (Player sits way over the dragon + the dragon can fly through everything)
* Note:  spelling of 'dragon' incorrect in description.
- Slime, maybe change to a big one
- Rudolph, fix ears
* Minor thing that can be fixed in config, the color of the last letter.
- Molten snake, remove odd floating block in the air

Over all Description text - change to be a little friendlier/less demonic suggestions:
* infernal horror mount - Change to "This mount comes directly from the flames!"
* summon inferno particles - Change to "Effect created by a dark lord/knight"
* summon bloodhelix particles - Change to "Red Helix", maybe?
* summon Frozen walk particles - Change to snow blocks that you walk on?

![2016-06-25_17 41 30](https://cloud.githubusercontent.com/assets/10177986/16357631/756868c2-3afc-11e6-8827-be40ac18e2a8.png)

**Comment by iSach** [comment]
Thanks for providing all the erorrs like that.
But to fix, I really need more detailed informations.

**Comment by TheChampTF** [comment]
On git-Spigot-687a019-f068c5e (MC: 1.10.2)

True, but always trying to see if things can be improved or adjusted (:

**Comment by iSach** [comment]
Pets section:

- Fixed
- Fixed
- Fixed
- Fixed
- Fixed

Gadgets:

- Gadgets aren't supposed to be used anywhere else than hub, so disable it.
- Changed to Packed.
- It doesn't stay 75 seconds, that's normal. any precise infos about not despawning?

Mounts:

- That's normal. Minecraft doesn't allow to ride an entity under water.
- See above.
- Normal. Dragons doesn't get blocked by blocks.
- Fixed.
- Changed to a 3-sized slime.
- Can't make them better placed.
- Color of last letter? I need those "things that can be fixed".
- Fixed

**Comment by TheChampTF** [comment]
All the trampolines on the photo^ is from the different times me placing one, they did not respawn after each use.

Last letter is in 'Rudolph' it's red (Not sure if on purpose)

Thanks for the quick fixing.

**Comment by iSach** [comment]
I need to know how to reproduce Trampoline bug. I tried Trampoline and it despawned fine.
A derp?

Also caused by Minecraft.
It's on purpose, as Rudolph's nose is red.
Tfried the size above, was not better
