### ISSUE TITLE
cosmetic chest suggestion

### ISSUE THREAD

**Issue by CakeLady** [iSach/UltraCosmetics#131]
I have looked all over and not found a way to remove the chest from the player's inventory without removing their perms.  If it doesn't already exist, can there be an ig command players can use to get the chest and then remove it from their inventory when they are done using it?  Or a command that goes straight to the GUI without needing the chest at all?  

Thanks for all your hard work on this awesome plugin! Everyone loves it!

**Comment by iSach** [comment]
In Config, disable Give-on-Join for the chest
