### ISSUE TITLE
Normal spiders behavior

### ISSUE THREAD

**Issue by Lbleu** [iSach/UltraCosmetics#132]
They do not attack or move, they just stare at you and nothing else (spigot 1.10 server)

**Comment by alekso56** [comment]
Are you in creative? >_>

**Comment by Lbleu** [comment]
Obviously not and even if I were on creative, they should move around right?

**Comment by iSach** [comment]
This must be fixed.

**Comment by iSach** [comment]
Fixed, will be included in next version.
