### ISSUE TITLE
EnderDragon problem

### ISSUE THREAD

**Issue by TheChampTF** [iSach/UltraCosmetics#134]
http://paste.yu8.me/?95e14ec97daf28d2#LHUqZKcUZ3Rp6ADZItO/ZAuY0dt9A5t+us1LEVU0z3w=

**Comment by iSach** [comment]
Are you sure it comes from EnderDragon? I don't see what could cause that.

**Comment by TheChampTF** [comment]
It happend(s) when it's turned on

**Comment by iSach** [comment]
Spigot version?

**Comment by TheChampTF** [comment]
git-Spigot-5391d73-00359a1 (MC: 1.10.2)

Not sure if https://github.com/iSach/UltraCosmetics/issues/133 is related, but might be.

**Comment by iSach** [comment]
EnderDragon tested on 1.10.2.
No crash.
Are you sure it comes from UltraCosmetics?

**Comment by TheChampTF** [comment]
Yea, it was the same issue with the wither. So seamed to be a flying type issue, maybe another conflict with NCP?

**Comment by iSach** [comment]
I don't think so. Could you try without any other plugins?
