### ISSUE TITLE
Add config to turn off Wither shooting

### ISSUE THREAD

**Issue by ataranlen** [iSach/UltraCosmetics#135]
The Wither pet on 1.8.9, 1.9.4, and 1.10 will still shoot. This is undesirable, as a players pet could kill them.

I'd like to request an option to turn off the attack of a wither pet.

**Comment by iSach** [comment]
It's not supposed to shoot.
Is the Wither big or small?

**Comment by iSach** [comment]
Tested on 1.8.8, 1.9.4 and 1.10. Wither doesn't shoot.
