### ISSUE TITLE
Request of more pets

### ISSUE THREAD

**Issue by TheChampTF** [iSach/UltraCosmetics#138]
Ideas:
Iron Golem
Snow Golem
Slime
Squid
Villager
Bat
Horse
Enderman
Zombie Pigman
Spider
Blaze
Cave Spider
Creeper
Ghast
Magma Cube
Silverfish
Skeleton
Spider Jockey
Zombie
Zombie Villager
Wither Skeleton 
Witch
Endermite
Guardian
Elder Guardian
Killer Rabbit 
Pigman Jockey
Baby Zombie
Shulkers
Skeleton Trap Horse
Polar bear
Husk
Stray

**Comment by iSach** [comment]
Entities only available on one version won't be added.
Thanks for suggestions, they've been noted. just closing issue to clean a bit.
