### ISSUE TITLE
Pet issue

### ISSUE THREAD

**Issue by TheChampTF** [iSach/UltraCosmetics#140]
Hey

So today I was trying to open a chest and notice a issue with my pet was being pushed away from me.

(EcoPet btw)

![pxslqyx](https://cloud.githubusercontent.com/assets/10177986/16430325/5215dfc2-3d7b-11e6-9489-739a0e7db976.png)

**Comment by iSach** [comment]
It's normal, all entities trying to enter the Treasure Chest Zones are kicked out.

**Comment by TheChampTF** [comment]
Any chance for a work around?

**Comment by iSach** [comment]
About what? It's normal not to let entities enter zone

**Comment by TheChampTF** [comment]
Just looks silly with ones pet pouncing all over.

**Comment by iSach** [comment]
I see, but I don't think letting it enter is better.
