### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by TheChampTF** [iSach/UltraCosmetics#141]
I was in creative and moved it to my survival inventory rather than my hotbar
Then I managed to stack two so I moved them again to see if they'd go away but they didn't.

Shift clicked to move up to inventory

I cloned it (like a normal gmc item) and got stuck with 64 of them, but when I tried to shift click the stack into my survival inv I got another glitch one there if that's any help.

![01](https://cloud.githubusercontent.com/assets/10177986/16431684/0346f1f4-3d82-11e6-8e6f-1f9cbb368786.jpeg)

**Comment by iSach** [comment]
Creative "allows" bypassing the cancellation of Item Clicking. Can't do anything.

**Comment by iSach** [comment]
The best is not to use UltraCOsmetics in Creative, or when in creative not trying to move the chest etc.
