### ISSUE TITLE
Christmas Elf bug

### ISSUE THREAD

**Issue by TheChampTF** [iSach/UltraCosmetics#143]
For some reason there is a 'text' stuck in a wall (not even a location I recall being at ever)

Have tried to clear it as normaly done in the plugin + restart server.

It's still there 
![2016-06-30_16 46 18](https://cloud.githubusercontent.com/assets/10177986/16492881/b736a954-3ee3-11e6-8de4-6f5331c8a853.png)

![2016-06-30_17 38 16](https://cloud.githubusercontent.com/assets/10177986/16494488/c9d0300c-3ee9-11e6-8b89-c54c2fd15b9d.png)

**Comment by iSach** [comment]
This should be fixed;
Next version will include the fix.
