### ISSUE TITLE
Mounts/Pets not working

### ISSUE THREAD

**Issue by hoopzah** [iSach/UltraCosmetics#155]
I tried to see on the Wiki a fix for mounts despanwing but couldnt, and pets isnt working either,

here is a GIF of what happens: https://gfycat.com/FlickeringPresentElephantbeetle

Config: http://pastebin.com/uySPgR7C

**Comment by iSach** [comment]
Must be a plugin conflict

**Comment by hoopzah** [comment]
hmm, 
Plugins:
AlwaysDay
AsyncWorldEdit
AutoDoor
AutoPickup
AutoUpdater
BossShop
ChatColor
ClearLag
ColoredSigns
ConnectFourReloaded
CoreProtect
CratesPlus
CS-CoreLib
CustomScoreboard
DropsToInventory
EnjinMinecraftPlugin
Essentials
EZPrestige
EZRanksLite
HolographicDisplays
LibsDisguises
MinesResetLite
Multiverse-Core
NickNamer
NoCheatPlus
PermissionsEx
PlayerVaults
PlotSquared
PluginMetrics
PlugMan
ProtocolLib
RainbowArmor
RewardVoting
ServerSpawn
UltraCosmetics
Updater
Vault
Votifuer
WorldEdit
WorldGuard


would any of those effect it?

**Comment by iSach** [comment]
I don't know, try with only UltraCosmetics

**Comment by hoopzah** [comment]
It works on its own, strange.

**Comment by zorvi** [comment]
I has it to it is worldguard if you set animals off they dont spawn
