### ISSUE TITLE
"Name's pet" stay

### ISSUE THREAD

**Issue by Mrcoco29** [iSach/UltraCosmetics#159]
Hi,
I try your plugin, and I have cleaned my pet. But the name of the pet stay in the world, without the pet. How I can do for remove this ?
Thank,
Mr_coco29

- sorry for my english. If you see mistakes, tell me, I want improve my english :p

![2016-07-12_19 04 21](https://cloud.githubusercontent.com/assets/7692756/16775989/7e599b26-4863-11e6-9bd9-bd9e3eab29cc.png)

**Comment by Mrcoco29** [comment]
Ok sorry.

I use in a command block "/minecraft:kill @e[type=ArmorStand,r=5]" 
I think if the name stay, it was a mishandling of me, not a bug of the plugin.

Have a nice day !

**Comment by iSach** [comment]
It's a bug from the plugin. :p
