### ISSUE TITLE
1.10.2 UC 2.3.4 slimes are not moving

### ISSUE THREAD

**Issue by i9hdkill** [iSach/UltraCosmetics#160]
In UC 2.3.4 and spigot 1.10.2 slimes are pinned to the ground.

How to reproduce this:

clean spigot 1.10.2 (from today)
UC 2.3.4
watch natural slime spawning or use a slime spawnegg.
(summon works fine)

**Comment by iSach** [comment]
hello, seems that my custom entities are overriding default ones. Happens also with spider.
I'll fix that asap.

**Comment by iSach** [comment]
Fixed in commit: fd70ddf92ed0dce7127941aabe9695ccd9615145.
