### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by ArtutoGamerYT** [iSach/UltraCosmetics#162]
When I select a Morph on the GUI in CONSOLE spams this:

`20:35:29
 CONSOLE:
WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
20:35:29
 CONSOLE:
WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
20:35:29
 CONSOLE:
WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
20:35:29
 CONSOLE:
WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
20:35:29
 CONSOLE:
WARN]: at be.isach.ultracosmetics.cosmetics.morphs.MorphType.equip(MorphType.java:98)
20:35:29
 CONSOLE:
WARN]: at be.isach.ultracosmetics.manager.MorphManager$3.run(MorphManager.java:171)
20:35:29
 CONSOLE:
WARN]: at be.isach.ultracosmetics.manager.MorphManager.equipMorph(MorphManager.java:173)
20:35:29
 CONSOLE:
WARN]: at be.isach.ultracosmetics.manager.MorphManager.morphSelection(MorphManager.java:283)
20:35:29
 CONSOLE:
WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:35:29
 CONSOLE:
WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:35:29
 CONSOLE:
WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:35:29
 CONSOLE:
WARN]: at java.lang.reflect.Method.invoke(Method.java:497)
20:35:29
 CONSOLE:
WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
20:35:29
 CONSOLE:
WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
20:35:29
 CONSOLE:
WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
20:35:29
 CONSOLE:
WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
20:35:29
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630)
20:35:29
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
20:35:29
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
20:35:29
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
20:35:29
 CONSOLE:
WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
20:35:29
 CONSOLE:
WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20:35:29
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
20:35:29
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
20:35:29
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
20:35:29
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
20:35:29
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
20:35:29
 CONSOLE:
WARN]: at java.lang.Thread.run(Thread.java:745)
20:35:29
 CONSOLE:
WARN]: java.lang.reflect.InvocationTargetException
20:35:29
 CONSOLE:
WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
20:35:29
 CONSOLE:
WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
20:35:29
 CONSOLE:
WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
20:35:29
 CONSOLE:
WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
20:35:29
 CONSOLE:
WARN]: at be.isach.ultracosmetics.cosmetics.morphs.MorphType.equip(MorphType.java:98)
20:35:29
 CONSOLE:
WARN]: at be.isach.ultracosmetics.manager.MorphManager$3.run(MorphManager.java:171)
20:35:29
 CONSOLE:
WARN]: at be.isach.ultracosmetics.manager.MorphManager.equipMorph(MorphManager.java:173)
20:35:29
 CONSOLE:
WARN]: at be.isach.ultracosmetics.manager.MorphManager.morphSelection(MorphManager.java:283)
20:35:29
 CONSOLE:
WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:35:29
 CONSOLE:
WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:35:29
 CONSOLE:
WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:35:29
 CONSOLE:
WARN]: at java.lang.reflect.Method.invoke(Method.java:497)
20:35:29
 CONSOLE:
WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
20:35:29
 CONSOLE:
WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
20:35:29
 CONSOLE:
WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
20:35:29
 CONSOLE:
WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
20:35:29
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630)
20:35:29
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
20:35:29
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
20:35:29
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
20:35:29
 CONSOLE:
WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
20:35:29
 CONSOLE:
WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20:35:29
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
20:35:29
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
20:35:29
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
20:35:29
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
20:35:29
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
20:35:29
 CONSOLE:
WARN]: at java.lang.Thread.run(Thread.java:745)
20:35:29
 CONSOLE:
WARN]: Caused by: java.lang.NullPointerException
20:35:29
 CONSOLE:
WARN]: at me.libraryaddict.disguise.disguisetypes.Disguise.createDisguise(Disguise.java:124)
20:35:29
 CONSOLE:
WARN]: at me.libraryaddict.disguise.disguisetypes.MobDisguise.<init>(MobDisguise.java:31)
20:35:29
 CONSOLE:
WARN]: at me.libraryaddict.disguise.disguisetypes.MobDisguise.<init>(MobDisguise.java:19)
20:35:29
 CONSOLE:
WARN]: at be.isach.ultracosmetics.cosmetics.morphs.Morph.<init>(Morph.java:55)
20:35:29
 CONSOLE:
WARN]: at be.isach.ultracosmetics.cosmetics.morphs.MorphWitherSkeleton.<init>(MorphWitherSkeleton.java:30)
20:35:29
 CONSOLE:
WARN]: ... 28 more
20:35:37
 CONSOLE:
[INFO] ArtutoGamer issued server command: /disguise
20:35:41
 CONSOLE:
WARN]: java.lang.IllegalArgumentException: No suitable constructor could be found.
20:35:41
 CONSOLE:
WARN]: at com.comphenix.protocol.injector.PacketConstructor.withPacket(PacketConstructor.java:179)
20:35:41
 CONSOLE:
WARN]: at com.comphenix.protocol.injector.PacketFilterManager.createPacketConstructor(PacketFilterManager.java:923)
20:35:41
 CONSOLE:
WARN]: at me.libraryaddict.disguise.utilities.DisguiseUtilities.<clinit>(DisguiseUtilities.java:135)
20:35:41
 CONSOLE:
WARN]: at me.libraryaddict.disguise.DisguiseAPI.getDisguises(DisguiseAPI.java:419)
20:35:41
 CONSOLE:
WARN]: at me.libraryaddict.disguise.DisguiseAPI.undisguiseToAll(DisguiseAPI.java:480)
20:35:41
 CONSOLE:
WARN]: at be.isach.ultracosmetics.CustomPlayer.removeMorph(CustomPlayer.java:435)
20:35:41
 CONSOLE:
WARN]: at be.isach.ultracosmetics.CustomPlayer.clear(CustomPlayer.java:368)
20:35:41
 CONSOLE:
WARN]: at be.isach.ultracosmetics.manager.MainMenuManager$3.run(MainMenuManager.java:200)
20:35:41
 CONSOLE:
WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
20:35:41
 CONSOLE:
WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
20:35:41
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
20:35:41
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
20:35:41
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
20:35:41
 CONSOLE:
WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
20:35:41
 CONSOLE:
WARN]: at java.lang.Thread.run(Thread.java:745)
20:35:41
 CONSOLE:
WARN]: Caused by: java.lang.RuntimeException: Detailed error com.comphenix.protocol.injector.BukkitUnwrapper@2a176478: com.comphenix.protocol.error.Report@5d99d696
20:35:41
 CONSOLE:
WARN]: at com.comphenix.protocol.error.RethrowErrorReporter.reportDetailed(RethrowErrorReporter.java:51)
20:35:41
 CONSOLE:
WARN]: at com.comphenix.protocol.error.RethrowErrorReporter.reportDetailed(RethrowErrorReporter.java:46)
20:35:41
 CONSOLE:
WARN]: at com.comphenix.protocol.injector.BukkitUnwrapper.getFieldUnwrapper(BukkitUnwrapper.java:230)
20:35:41
 CONSOLE:
WARN]: at com.comphenix.protocol.injector.BukkitUnwrapper.getSpecificUnwrapper(BukkitUnwrapper.java:186)
20:35:41
 CONSOLE:
WARN]: at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:109)
20:35:41
 CONSOLE:
WARN]: at com.comphenix.protocol.injector.PacketConstructor.withPacket(PacketConstructor.java:143)
20:35:41
 CONSOLE:
WARN]: ... 14 more`

I have installed Lib's Disguises and ProtocolLib

**Comment by iSach** [comment]
Wrong versions of them.

**Comment by iSach** [comment]
Correct versions can be found on the wiki.
