### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by DynamicThijs** [iSach/UltraCosmetics#164]
When typing /uc menu main, the menu does not open and the console logs this error: http://pastebin.com/jiWm3Me2
I'm running the latest version of UltraCosmetics and the latest version of Spigot

**Comment by DynamicThijs** [comment]
Also /uc gadgets does not work, it does not give me an error, just nothing happens.
And /uc selfview is broken too, however this one gives me an error in the console: http://pastebin.com/U2XcqVEV

**Comment by DynamicThijs** [comment]
And another broken command, this time the /uc treasure command. It does not work and gives me this console error: http://pastebin.com/Z76tzLdQ

**Comment by DynamicThijs** [comment]
I think the whole command system is bugged. You should take a look at it :)

**Comment by DynamicThijs** [comment]
And on every player join, the console says:
UltraCosmetics ERR -> SQLLoader Fails to preload UUID: <uuid of the player that joined>

**Comment by iSach** [comment]
not related to Commands.
Problems with MySQL.

**Comment by DynamicThijs** [comment]
MySQL?
Don't have that enabled

**Comment by PatoTheBest** [comment]
Post your config and your startup log

**Comment by DynamicThijs** [comment]
Resolved in the latest update
