### ISSUE TITLE
[Request with A Bug] Squid Bug | Command Request | Hat Names?

### ISSUE THREAD

**Issue by cervinakuy** [iSach/UltraCosmetics#165]
Hello!

So when using the Squid Mount, you constantly hear a Splash Potion being thrown somewhere, please fix this, as it's pretty annoying to my players.

Would you be able to add a command to put on an entire suit? This would be ideal since I want to create my own GUI with Chest Commands but can't put on an entire suit.

Could I also get the Hat player names? Like I said, I want to create a menu with Chest Commands but I would need the Hat player names for the items in the GUI.

Thank you! :)

Cervinakuy

**Comment by iSach** [comment]
For the Squid, I'll try to find a way to display praticles without sound.

You can't execute mulitple commands?

It's not player names, it's a texture on Mojang Servers as they don't delete Skins from their servers.

**Comment by cervinakuy** [comment]
Okay.

Oh, I didn't see the commands, thanks! :)

So do you know if it would be possible to somehow get a player head like the ones shown in the UltraCosmetics hats menu that I can place on the ground, and use in menus and such?

**Comment by iSach** [comment]
I don't think ChestCommands has a command to use Texture Links.
