### ISSUE TITLE
MySQL Error with latest version, but no error with earlier versions?

### ISSUE THREAD

**Issue by cervinakuy** [iSach/UltraCosmetics#166]
Hello!

So basically, today I decided I would update UltraCosmetics since there were a lot of fixes. However, when I did so, I got [this](http://hastebin.com/etuvucuzom.coffee) with version 2.3.6 AND 2.3.5. However, 2.3.4 worked fine no errors.

Could you please fix the problem?

Thank you!
Cervinakuy

**Comment by JustMaffie** [comment]
This problem is already known to us and we're trying to fix it.

**Comment by cervinakuy** [comment]
Okay great, thank you!
