### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by JamiePlayzMC** [iSach/UltraCosmetics#167]
I was wondering for the pets would it be possible for you to use the world guard api so that if you have world guard turning off natural mob-spawning, pets/mounts can still spawn this would be really useful as animals are spawning around the hub, thanks.

**Comment by iSach** [comment]
I used a method to bypass, if it doesn't work I don't see how to.

**Comment by altrisi** [comment]
To prevent animals spawning just set the gamerule doMobSpawning to false. Gamerules work per world.
