### ISSUE TITLE
How to enable pets/mounts while preventing mobs/animals from spawning?

### ISSUE THREAD

**Issue by Thetax128** [iSach/UltraCosmetics#174]
So, I'm making a lobby world for a minigames/other game modes server and  I want to make it so I can prevent animals and hostile mobs from spawning but still allow pets and mounts. is there any way to make this work? Some of the plugins that I have that might be relevant to this issue would be

-Essentials
-Multi-Verse
-LibDisguises
I'm running some other plugins as well. If you need any more information just ask!

Thanks in advanced!

**Comment by altrisi** [comment]
It's simple. Keep the multiverse settings of animals and monsters to true, but set the gamerule doMobSpawning to false. Gamerules work per world.

**Comment by Thetax128** [comment]
Thank you so much! I'll test if it works.

**Comment by Thetax128** [comment]
Update! Works like a charm. I owe you my left testicle altrisi. Thanks.

**Comment by Thetax128** [comment]
Can a mod lock post?

**Comment by altrisi** [comment]
Think you can close it by clicking the button next to the comment button, it say something like "Close".
