### ISSUE TITLE
Sky Squid Error

### ISSUE THREAD

**Issue by altrisi** [iSach/UltraCosmetics#175]
On the latest version, when you try to spawn the Sky Squid, it says "You spawned Sky Squid", but any squid is spawned. The player stays floating in a possible invisible entity, and he can't move. Any error in console. The player only can move if he dismount with Shift or despawn the entity with the menu button. In all of them cases, it says the normal message "You despawned Sky Squid".

**Comment by iSach** [comment]
Please try with latest version. Reopen if still not working.

Sky Squid only works in 1.8.8 and below.
