### ISSUE TITLE
[Demande] Possibilité de rien trouvé.

### ISSUE THREAD

**Issue by dearvoodoo** [iSach/UltraCosmetics#198]
Bonjour je viens faire une demande si c'est possible :)
Au passage je me permets de parler français j'ai cru comprend que le dev était belge donc bon ^^

Ma demande est la suivante: Je voudrais savoir s'il était possible d'ajouter le loot "Rien" dans les treasure chest. Ce serais sympa que les joueurs trouvent rien de temps en temps à la place de tout le temps loot de l'argent ou autres.

Merci à vous
VooDoo

**Comment by iSach** [comment]
Bonjour, désolé de ce délai de réponse j'ai pas vu cette issue je suppose. L'objet a été ajouté depuis, c'est bon comme ça ? Ou tu voulais qu'il soit intégré autrement ?
