### ISSUE TITLE
Using MySQL does not transfer permissions. Can you add this?

### ISSUE THREAD

**Issue by ReasonWhyGamer** [iSach/UltraCosmetics#206]
Could you implement a permissions table into MySQL and make it so when someone gets a permission from a treasure chest they essentially get the permission on all connected MySQL servers?
This would be a fantastic thing and I will start using the plugin again when this gets implemented.
I'm not using the plugin right now because of this.

**Comment by iSach** [comment]
UltraCosmetics doesn't a and won't manage permissions, just use a permissions plugin that supporte MySQL like Pex

**Comment by ReasonWhyGamer** [comment]
It's fine I can work around this. Great plugin btw :) also when players
join for the first time the MySQL adds them to the database and let's me
change stuff but they have to rejoin for that to apply. This is only first
time ever joiners.
