### ISSUE TITLE
Problem with emotes!

### ISSUE THREAD

**Issue by Waterman1001** [iSach/UltraCosmetics#211]
I really love this plugin but I found a bug. Hopefully you can help me? :)

When you use an emote and then go to another world (where UC is disabled) without unequipping it, the next time you go to that world the head of the emote is stuck on your head. You cannot get it off anymore.
Thanks in advance for your response!

Edit: The same is happening for hats and suits :c

**Comment by iSach** [comment]
Does it still happen in last nightly builds? ci.isach.be

**Comment by iSach** [comment]
Closing until response.
