### ISSUE TITLE
Specific Settings for Mounts

### ISSUE THREAD

**Issue by MorenaDaniel** [iSach/UltraCosmetics#212]
Is it possible to customize the settings of the mounts ? (Speed, block placed etc...)

Thanks

**Comment by StrangeOne101** [comment]
I'd also like settings for things like enderdragons going through blocks. This can be abused a lot on faction servers, so small settings like this would be a great addition.

**Comment by Jocke155** [comment]
Mounts should have an option where they just spawn, and can't be moved anywhere by the player, but still have the particle effects etc.

**Comment by datatags** [comment]
> Is it possible to customize the settings of the mounts ? (Speed, block placed etc...)

This is a good idea





> I'd also like settings for things like enderdragons going through blocks. This can be abused a lot on faction servers, so small settings like this would be a great addition.

I don't think this is possible without some serious internals work. I'd say if dragons flying through blocks is an issue, you should disable the mount.



> Mounts should have an option where they just spawn, and can't be moved anywhere by the player, but still have the particle effects etc.

This seems doable
