### ISSUE TITLE
Request. For German People

### ISSUE THREAD

**Issue by soulgamerhd** [iSach/UltraCosmetics#23]
Hey there.

Is it possible for you to edit the messages.yml (don't know how) that it's possible to use ä ü ö for the german translation. I would send you a german messages file then. so the german users maby could download it.

EDIT: It is possibe to make a variable. For example: you can say in the code that every "%u%"
         (or something like this) will be replaced by a "ü".

Thanks in Advance
Marvin

**Comment by iSach** [comment]
Messages File should be Encoded in UTF-8 so those characters should already work.

**Comment by soulgamerhd** [comment]
I tried it and if i for example write "überall" then there stands this 
![2016-01-06_18 31 40](https://cloud.githubusercontent.com/assets/7301498/12149511/4c129e4a-b4a4-11e5-87de-50c70eac635a.png)

**Comment by soulgamerhd** [comment]
oops

**Comment by soulgamerhd** [comment]
More Bugs:

1. Ethernal Pearl Ports you if you leave it with a crouch.
2. Freeze Bomb Block is catchable
3. Is it possible for me to deaktivate mob-spawning without deactivating "Sheep Bomb", "Ghost Party" 
  etc.? 
Because when i deactivate Mob-Spawning with WorldGuard i cant see the sheeps or ghosts      and all the mounts.

Thanks in Advance
Marvin

**Comment by iSach** [comment]
It's surely a problem with your server encoding, or the file on your server. Because I can put accent on my side.


Deactivate with the game rule but allow with WorldGuard.
