### ISSUE TITLE
Get Free item via Item Frame

### ISSUE THREAD

**Issue by scabbed** [iSach/UltraCosmetics#231]
hello,

if you take for example disco ball gadget, you put in in item frame, you cancel the gadget, then you can take it back in the frame. And you have free beacon :) so for survival server, its free beacon ^^ 

can you disable gadget item in item frame ??

thanks

**Comment by iSach** [comment]
Fixed in Beta Build #58.
Gadgets can't be put anymore in Item Frames.

**Comment by scabbed** [comment]
hmm sorry but i still can put gadget in item frame, with the last build :(

[http://img4.hostingpics.net/pics/42043020170312103249.png](url)
