### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by sauceadmiral** [iSach/UltraCosmetics#25]
I have the same problem as @soladev. The chest is in my hotbar but it doesn't do anything. I can open the main menu with commands but the Items act like regular chest items that I can take out. Typing almost any command returns "Internal error." I have the latest version of the plugin, Vault, ProtocolLib, and Lib's Disguises. I am using Spigot 1.8.8. I also am opped AND have the correct permission. Please help!

P.S. I tried an older version (1.3.4) and it works fine. Any version beginning with "2" yields the problem.

**Comment by iSach** [comment]
Still having this?
