### ISSUE TITLE
ItemFlags in icons' lores

### ISSUE THREAD

**Issue by MrBrikster** [iSach/UltraCosmetics#266]
Lores of menu's icons have the item flags (such as "Damage", "Attack Speed" and the other).

I'm using this code for fix:
```
ItemMeta itemMeta = itemStack.getItemMeta();
itemMeta.addItemFlags(ItemFlag.values());
itemStack.setItemMeta(itemMeta);
```

**Comment by iSach** [comment]
Thanks for the fix, gonna try it

**Comment by iSach** [comment]
I'm still getting the damage etc with this 1.11, strange.
https://puu.sh/vjggw/428a4c7905.png

**Comment by MrBrikster** [comment]
Strange... I added this code to Menu.java, method "putItem" and have no damage etc...

**Comment by MrBrikster** [comment]
http://prntscr.com/ew4h25

**Comment by iSach** [comment]
My bad, I didn't put the "local" boolean of my build.gradle to true so it wasn't updating the jar. :p 

It works perfectly thanks for your help on this!
