### ISSUE TITLE
Mob spawning off

### ISSUE THREAD

**Issue by Luuk5991** [iSach/UltraCosmetics#30]
Hey there!
I have a question about in WorldGuard and UltraCosmetics.
In my hub server I want to turn off mob spawning so there don't spawn mobs but when I do this I also can't spawn mobs from UltraCosmetics anymore so now my question is how can I turn off mobspawning but still use UltraCosmetics?

**Comment by StaticCraft** [comment]
To do this you need to allow mob/animals spawning in multi-verse and deny mob/animals spawning in the server.properties the reason why this doesn't work with multi-verse is that it deny's mobs/animals being spawned in the world in any way what so ever but with server.properties it just deny's the spawning of the mob/animal.
Thanks
Steven
