### ISSUE TITLE
Disco ball remains active

### ISSUE THREAD

**Issue by Carbonawk** [iSach/UltraCosmetics#304]
When one disco ball is used, another cannot be used until server reboot.

This server is running CraftBukkit version git-Spigot-28463de-a2af8f0 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

Error message ""error" There is already a disco ball active!"

![xnf6jph 1](https://cloud.githubusercontent.com/assets/25295327/26283298/ebacb5f6-3e25-11e7-949b-cc7ec2253c51.jpg)

**Comment by iSach** [comment]
Fixed in 2.4.5
