### ISSUE TITLE
Serious Bug: Pig Morph permanently disabling player collisions

### ISSUE THREAD

**Issue by MidnightSugar** [iSach/UltraCosmetics#305]
There is a serious bug if a player uses the pig morph, they no longer have collision. They can no longer push other players or animals around. I tried a server restart and resetting their player data files, and it not fix it.

**Comment by iSach** [comment]
I can't reproduce it. 
Please try with no other plugins, what is your spigot version?

**Comment by MidnightSugar** [comment]
I used:
- Spigot 1.11.2 latest
- UltraCosmetics 2.4.5
- LibsDisguises 9.3.0
- ProtocolLib 4.2.1

I just tested it on my test server, and it is still removing my collisions.

**Comment by MidnightSugar** [comment]
EDIT: I just deleted all my files and started fresh and it seems to be working now. I will do more testing to see what is causing it...
