### ISSUE TITLE
How to use open source?

### ISSUE THREAD

**Issue by Reimzon** [iSach/UltraCosmetics#306]
Hello! Maybe someone will seem ridiculous, but how to use open source?
P. S: This text is written with the help of an interpreter. (May be errors)

**Comment by iSach** [comment]
Hello,

I can't help with Eclipse, but you can use IntelliJ IDEA Community Edition (free and complete) to import the build.gradle and start developing the project.

Importing the repositery:
https://www.jetbrains.com/help/idea/2017.1/cloning-a-repository-from-github.html

Importing the gradle project:
https://www.jetbrains.com/help/idea/2017.1/importing-a-gradle-project-or-a-gradle-module.html

**Comment by Reimzon** [comment]
Thank

**Comment by iSach** [comment]
No problem :)
