### ISSUE TITLE
Error when player loging at hub

### ISSUE THREAD

**Issue by xion87** [iSach/UltraCosmetics#31]
sometimes at player login it spam this error:
http://hastebin.com/sicamanoqo.apache

It never happened before 2.0 version (xmas update)

**Comment by iSach** [comment]
Is your server offline mode?

**Comment by xion87** [comment]
say yep is in offline mode, both bungee and server

**Comment by iSach** [comment]
Okay, i will do some testing, what is annoying with offline mode is UUID changes and there are problems etc
