### ISSUE TITLE
Item stuck in inventory (not a bug)

### ISSUE THREAD

**Issue by tochjunin** [iSach/UltraCosmetics#32]
Hello, sorry i really didnt want to bother you, and this is not even a bug, but indeed it is something that is making some trouble.

So

Is there any way to remove the menu-item from the bind slot?
Because its really annoying to have that item killing your item slot, making it exclusive for cosmetics.

its been some hours that im tinkering and searching anything to help me with that... (with no luck)

Is there anything to remove that item? or make it "slot-changeable", even a command like:

/uc menu-item off/on

Sorry to bother, and thx any advice!

**Comment by tochjunin** [comment]
I found out a way to deal with this. if anyone here have the same issue as me, it might help.

its not optmal, but really solve things.

I downloaded another plugin called "item commands", them i made a item with ender_chest look, them i made this item trigger the command "uc menu main" when used.

The ender_chest is not bind on my item slot anymore, i can move it, and even throw away.

**Comment by iSach** [comment]
You can just disable the main menu item from config;
