### ISSUE TITLE
Lack of per-world inventory support

### ISSUE THREAD

**Issue by Bumbullbee** [iSach/UltraCosmetics#330]
Hello! Recently I've noticed a problem when a player has a gadget activated and they leave to another world, in which they have another inventory. (specific to that world) The Gadget deactivates like it's supposed to, but the item itself doesn't get removed. This leads to a problem where the gadget turn into actual items that stay in the inventory in the initial world. (The one the gadget was used in)
All of this is due to per-world inventories.

**Comment by iSach** [comment]
This looks to be a conflict :/ 
Will investigate.

**Comment by iSach** [comment]
If this still isn't working in 2.5.1, please re-open.
