### ISSUE TITLE
When you die, cosmetic itens drop.

### ISSUE THREAD

**Issue by tochjunin** [iSach/UltraCosmetics#36]
Hello again!

Now im here for a real bug.

When you equip something in suits or gadgets, and die, they drop.
Them other people can take it. You cant use them, thats fine, but, in servers with selling features, this become a huge problem.

I can equip myself with diamond armor set, and fall from somewhere, die, drop everything (including cosmetic suits and gadgets) them get these drops and sell all of them, and repeat this process how many times i want.

Someone did it in my server, them i turned off some items in cosmetics because of this, and removed the sell capabilities for some other items.

even so, awesome plugin btw, congrats and thx :)

**Comment by JHXSMatthew** [comment]
Should be fixed in recent updates anyway.
 I found code related to this issue.
line 155 in PlayerListener
Do you still have those issues ?

**Comment by iSach** [comment]
Please reopen issue if you still get this problem.
