### ISSUE TITLE
Mounts dismount bug.  

### ISSUE THREAD

**Issue by TheQce** [iSach/UltraCosmetics#37]
Hello thanks for checking my report. I've been looking around in your wiki and I didn't find such annoying bugs This one is really annoying sometimes.
I tried restarting my server, worldediting it out but still
it's not getting removed.
How do Iremove the small blocks?

https://gyazo.com/292c230f2c733f72fef2894afdb56eb1

**Comment by iSach** [comment]
Did the server crash while the mount was there?

**Comment by TheQce** [comment]
No but i was reloading the plugin which is the same thing.

**Comment by iSach** [comment]
Reloading with Plugman?

**Comment by TheQce** [comment]
Yes, i assume that caused the bug but the problem is how do i remove that invisible mini block??

**Comment by iSach** [comment]
I don't do support for reloading plugin with Plugman, it's absolutely unsafe.

Go near them and type /kill @e[type=ArmorStand,r=12]
