### ISSUE TITLE
I need help with treasure chests

### ISSUE THREAD

**Issue by JaredDaMaster** [iSach/UltraCosmetics#38]
The problem is that when i get like a morph from a treasure chest it doesn't actually give it to me
I know why and it's because in the config i need to set the give permission command to the command ill use for group manager

I did manuadd %name% %permission%

But it still doesn't work
Any help?

**Comment by StaticCraft** [comment]
Try permissionsex might work just back up group manager if it goes south

**Comment by JaredDaMaster** [comment]
I really don't like permissionsex the commands are confusing and I've already setup all the permissions on GroupManager

**Comment by iSach** [comment]
GroupManager Is a bad and outdated plugin. It doesn't support UUIDs and doesn't have a lot of features that pex has. You shoud really switch.
