### ISSUE TITLE
Main Menu Not Working?

### ISSUE THREAD

**Issue by CreepUnderscoreE** [iSach/UltraCosmetics#39]
I just installed the newest version of Ultra Cosmetics, and when I opened up the cosmetics menu and clicked on gadgets and everything else, nothing happened and it printed this error into the console:
![rage](https://cloud.githubusercontent.com/assets/16739408/12375565/108ab066-bc96-11e5-99de-bc8ebbc3c828.png)

Can anyone help? I'm not sure what it is, and I have read through everything on the wiki

**Comment by iSach** [comment]
Use Spigot and CraftBukkit as said on wiki.

Has been fixed by Matthew Yu for next version.
