### ISSUE TITLE
Particles appearing when you crouch or jump

### ISSUE THREAD

**Issue by StuckinTheMud01** [iSach/UltraCosmetics#394]
So this is my idea: 
Once set up, when you crouch- specific particles appear on your screen. This can also be set to when you jump. 
To enable this, you would do /ucpa (ultracosmetics particle affects) 
This would open up a GUI (the same size as a chest) 
And you would have options such as, enable at the top and it’s red if the particles r not enabled and green if they are. 
And you would have particle effect as a blaze powder. When you open this then you get a whole ton of possible particle affects like love hearts and snowballs and nether stars, etc. 
But there could be a setting where you can set it as the particles happen to everyone in the server, and an option to set it to people with a certain permission node.
I’m not sure if this is possible, but having it set to certain words? So if you are using multiverse, you can select certain worlds this happens in? So say I have a lobby world- it happens in just that world, and not any other world. 
One last thing- we can submit .png files and they can appear on the screen? Just a small idea xD
Hope you add this, it could be really cool. Thanks, 
StuckinTheMud//George :)

**Comment by datatags** [comment]
This would be a whole new category of cosmetics which I don't think UC is ready for right now.

Cosmetics in certain worlds is already implemented.

As for uploading .png files, that sounds like it would require a whole different plugin to do well.

I'll close this for now, but maybe once UC is more stable we can revisit this.
