### ISSUE TITLE
Treasure Chests Restricted Areas

### ISSUE THREAD

**Issue by morgan2233** [iSach/UltraCosmetics#395]
Ok, can you please please add some sort of area which is designated to opening treasure chest because otherwise, they can block the spawn point etc or even better have an option where you can do it all via a GUI because i love the system but this will clog up my server

**Comment by datatags** [comment]
There are now two solutions to this. You can either set treasure chests to always open in one spot, meaning only one player can open a treasure chest at a time (see TreasureChests.Location in config.yml), or you can use the WorldGuard flag `uc-treasurechest` to prevent opening chests in specific areas, such as your server spawn.
