### ISSUE TITLE
NPE for Mount.

### ISSUE THREAD

**Issue by acecheese** [iSach/UltraCosmetics#4]
http://pastebin.com/ATgCBGHb

This occurs when you dismount something other than a mount.. The PR I made that added the try {} catch didn't work, it's getPlayer and Core#getCustomPlayer that make it weird.

**Comment by iSach** [comment]
Mmh okay thanks for the report I'll fix that

**Comment by iSach** [comment]
Fixed.

**Comment by acecheese** [comment]
Nope.

http://pastebin.com/H0mPqWc0 Same issue.

**Comment by iSach** [comment]
When does it happen?

**Comment by acecheese** [comment]
Not sure I suppressed it like in my fork. Seems to work suppressed without any side effects.

**Comment by acecheese** [comment]
The custom player could be null?

**Comment by iSach** [comment]
No I don't think so, normally that's impossible they are generated on enable and join and also the error happens on line initStats

**Comment by iSach** [comment]
Should be fixed for next version.
