### ISSUE TITLE
Pets issue

### ISSUE THREAD

**Issue by StaticCraft** [iSach/UltraCosmetics#40]
Hello,
When I selected a pet from the menu and then I restarted my server the pet would no longer be mine if I tried to clear pets it wouldn't clear it, it would let me select a new pet and leave the old one there.
Thanks
Steven

**Comment by StaticCraft** [comment]
And also there when I did the command "/killall animals" it got ride of the pet and left the hologram there could you help me to remove this hologram bearing in mine that I am using holographic displays
Thanks
Steven

**Comment by StaticCraft** [comment]
Hello, 
I have found a fix to this first kill the pet with the command "/killall animals" and then use "/entitydata @e[type=ArmorStand,r3] {Invisible:0}" then delete the armour stands and fixed
Thanks
Steven

**Comment by JHXSMatthew** [comment]
Any error ?

**Comment by iSach** [comment]
Would you know when exactly this happens?

**Comment by molocodev** [comment]
I had the same problem it was befor 2.0 but ISach i got a problem if i put the command /entitydata @e[type=ArmorStand,r3] {Invisible:0} i will delete the holograms from Holografic Displays any other solution?

**Comment by iSach** [comment]
The best solution would be to fix pets despawning. But I don't know when it really happens, what exact conditions.
