### ISSUE TITLE
Mounts bugs.

### ISSUE THREAD

**Issue by redfalcon5** [iSach/UltraCosmetics#420]
### What steps will reproduce the issue?  
1. Use Dragon mount
2. Use Slime mount
3. use Spider mount

### What was supposed to happen?
No errors.
### What happened? 
Dragon after spawn goes under the world and crashes the server after a bit.
Slime spawns stuck in the air.
Spider same as Slime.
### What version of UltraCosmetics are you using?  
2.4.12
### What Spigot version are you using? Paste the output of /version below.  
1.13.2
### What plugins do you have installed? Paste the output of /plugins below.  
Nothing important.
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
paste
error(s)
here
```
### Any additional information that you would like to provide that may be relevant to the issue?
No

**Comment by iSach** [comment]
Fixed in 2.5 and 2.5.1
