### ISSUE TITLE
Flesh hook issue with Parachute gadget 

### ISSUE THREAD

**Issue by Golicraft** [iSach/UltraCosmetics#426]
### What steps will reproduce the issue?  
1. Grab a Flesh Hook
2. Player 2 grab Parachute gadget
3. Player 1 shoot player2 with flesh hook

### What was supposed to happen?
The player will be boosted away
### What happened? 
The player dropped his lead (in hand) and the chickens fly in all ways of directions

### What version of UltraCosmetics are you using?  
Latest version

### What Spigot version are you using? Paste the output of /version below.  
Paperspigot 1.8.8

### What plugins do you have installed? Paste the output of /plugins below.  
No comment

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
Don't think so
```
### Any additional information that you would like to provide that may be relevant to the issue?
Picture: https://i.gyazo.com/2d827d5ea1f4a2373bf962beac240147.png

**Comment by iSach** [comment]
Will be included in 2.5.3
