### ISSUE TITLE
Suggestion: Load cosmetics on join again

### ISSUE THREAD

**Issue by Golicraft** [iSach/UltraCosmetics#427]
Hi there. May it please be a function that the players chosen cosmetic is saved when they log back online again. I know this may have been requested before but I couldn't find any clear answer "yes/no" Thank you for creating this masterpiece I am looking forward to donating in the future. 

Thank you in advance. Kind regards Goli

(( Sorry for re-post but I believe this is the only amazing future this plugin does not have and should have 🥇 ))

**Comment by iSach** [comment]
Duplicate of #182. 
It's planned
