### ISSUE TITLE
Translation ZIP-download: That puush could not be found.

### ISSUE THREAD

**Issue by xXSchrandXx** [iSach/UltraCosmetics#429]
### What steps will reproduce the issue?  
1. Try to download from: https://puu.sh/qWUfH/3efb7d0fd5.zip

### What was supposed to happen?
Download a ZIP linked in https://github.com/iSach/UltraCosmetics/wiki/Translations

### What happened? 
Website error:
```
That puush could not be found.
```

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
Not a UltraCosmetics error.
```

**Comment by iSach** [comment]
Puush has apparently indeed deleted the zip.

I don't have the files anymore. Waiting for a new translation file to upload.

**Comment by iSach** [comment]
Closing as I can't really do anything. I don't have the time to translate it sorry.
