### ISSUE TITLE
2 problems

### ISSUE THREAD

**Issue by ghost** [iSach/UltraCosmetics#432]
1)https://pastebin.com/N5ZBri9f   Bat blaster

2)when a player uses the anti-gravity gadget. When the effect ends, the server will hunt him for "fly". This only happens when the effect ends and a player is on top of it, it does not happen if a player comes out of the effect area.

**Comment by MineFriend** [comment]
another error: 

3) " [12:31:48 WARN]: java.lang.NullPointerException "  happens when you use the bat blaster (for now it only happens with this), when there is charging time sometimes stops and the armor is removed from the inventory and generates that error

**Comment by iSach** [comment]
Can you please try with latest UC version? Please close the issue if you stopped using UC.

**Comment by datatags** [comment]
Don't know what would cause this, but it seems to be working fine now.
