### ISSUE TITLE
Cant download 1.13.2 builds

### ISSUE THREAD

**Issue by Onyxtite** [iSach/UltraCosmetics#433]
Hey there, the plugin seems awesome but sadly i cant download a compatible build for my server. Could you please check the link to the dev builds? Thanks a lot :)

 What steps will reproduce the issue?  
Go to the link,
https://ci.isach.be/job/UltraCosmetics/lastBuild/
page wont' load :/

**Comment by PgBiel** [comment]
Here's a link for the 1.13.2 build I found on the Spigot discussion - https://mega.nz/#!ipcixSxY!g-111EY5TXZyMKbVesEuEN8m9UBwOMCJrbbg10I71eE

**Comment by Blamo27** [comment]
Official link (from UltraCosmetics server) : https://cdn.discordapp.com/attachments/288704498556207104/511053111079600128/UltraCosmetics-2.4.12-beta-2.jar

Or join the Discord, and check the "releases" channel

**Comment by iSach** [comment]
2.5 is now available
