### ISSUE TITLE
Chickenator destroys armorstands

### ISSUE THREAD

**Issue by Arkobat** [iSach/UltraCosmetics#434]
The gadget "Chickenator" can destroy armorstands.
https://gyazo.com/d6bdbbd73818799094a3656bf40f6c1e

Minecraft version: Paper 1.12.2 _(Paper version 1228)_
UltraCosmetic version: 2.4.11

There are no errors in the startup.
/plugins are completely blocked on our server, and therefore can't show it.
I can tell that we are using PlotSquared to manage plots.

**Comment by iSach** [comment]
Can you try on 2.5 please?

**Comment by iSach** [comment]
Should be fixed in 2.5
Please re-open if it's not. Sorry for the inconvenience and delay.
