### ISSUE TITLE
Problems with the custom menus

### ISSUE THREAD

**Issue by tochjunin** [iSach/UltraCosmetics#44]
Hello!

I got some weird bug.

for some weird reason, i can pick some itens from the menu...

i made this video to show what is going on:

https://www.youtube.com/watch?v=SvfKk5gsNr8&feature=youtu.be

The catch is:
This only happens when im in a multiverse world (made with the multiverse plugin).
When im in the first default world, it works just fine, but in the multiverse worlds, i have this bug...

Nether and The End, works ok.

**Comment by iSach** [comment]
No error?

**Comment by tochjunin** [comment]
@iSach 

No error at all.

i checked the console, and it dosnt show anything.

**Comment by JHXSMatthew** [comment]
I has this before !!!!
I used AdvancedLobby plugin for my lobby and this happens.
@iSach Remember ? We stay in my lobbys for hours and finally found this is caused by another plugin.

**Comment by dadus33** [comment]
@iSach I don't know about this guys, but I still have the issue :( It only happens when trying to take items from the slot WHILE THE CURSOR KEEPS MOVING! Pleas e help.

**Comment by JHXSMatthew** [comment]
Hi , please try to leave uc alone and see what's going on. If no issues are there  please try to put all plugin that would open a gui(inventory) in one by one and see what's the one conflict with uc. Note : known conflict plugin would be "advanced lobby".

**Comment by iSach** [comment]
Should not happen anymore, might have been caused by async selection.
