### ISSUE TITLE
Error when using the Bat Blaster Gadget

### ISSUE THREAD

**Issue by Waterman1001** [iSach/UltraCosmetics#444]
### What steps will reproduce the issue?  
1.  Use the bat blaster gadget
2. ..
3. ..

### What was supposed to happen?
Everything seems to work fine

### What happened? 
I got an error in the Console

### What version of UltraCosmetics are you using?  
2.5.0

### What Spigot version are you using? Paste the output of /version below.  
git-Spigot-798ea6a-368f4e9 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
`20.08 17:40:43 [Server] Craft Scheduler Thread - 25/WARN java.lang.NullPointerException
20.08 17:40:43 [Server] Craft Scheduler Thread - 25/WARN at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
20.08 17:40:43 [Server] Craft Scheduler Thread - 25/WARN at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
20.08 17:40:43 [Server] Craft Scheduler Thread - 25/WARN at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
20.08 17:40:43 [Server] Craft Scheduler Thread - 25/WARN at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
20.08 17:40:43 [Server] Craft Scheduler Thread - 25/WARN at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
20.08 17:40:43 [Server] Craft Scheduler Thread - 25/WARN at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
20.08 17:40:43 [Server] Craft Scheduler Thread - 25/WARN at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
20.08 17:40:43 [Server] Craft Scheduler Thread - 25/WARN at java.util.stream.ReferencePipeline.forEach(Unknown Source)
20.08 17:40:43 [Server] Craft Scheduler Thread - 25/WARN at be.isach.ultracosmetics.cosmetics.gadgets.GadgetBatBlaster.onUpdate(GadgetBatBlaster.java:66)
20.08 17:40:43 [Server] Craft Scheduler Thread - 25/WARN at be.isach.ultracosmetics.cosmetics.gadgets.Gadget.run(Gadget.java:142)
20.08 17:40:43 [Server] Craft Scheduler Thread - 25/WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
20.08 17:40:43 [Server] Craft Scheduler Thread - 25/WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
20.08 17:40:43 [Server] Craft Scheduler Thread - 25/WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
20.08 17:40:43 [Server] Craft Scheduler Thread - 25/WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)`
### Any additional information that you would like to provide that may be relevant to the issue?
n.a.

**Comment by iSach** [comment]
Hello, does this happen every time you use the gadget?

**Comment by Waterman1001** [comment]
I just checked, no it does not.
It happens as soon as I equip it and then activate it. The other times it just works.
Also I noticed that once I get it, the gadget automatically un-equips.
Thanks for your fast response!

**Comment by iSach** [comment]
Does 2.5.1 still produce this error?

**Comment by Waterman1001** [comment]
Yes it does. I am using version 2.5.2 now.
But I think I have found a way to reproduce it..
It does not always work but (since I am using a Launchpad plugin), often when activating the Bat Blaster at the moment JUST BEFORE stepping up the Launchpad and flying away away from the Launchpad, I get the error:

`23.08 00:34:35 [Server] Server thread/ERROR Could not pass event PlayerInteractEvent to UltraCosmetics v2.5.2
23.08 00:34:35 [Server] INFO org.bukkit.event.EventException: null
23.08 00:34:35 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:429) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:396) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:136) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1185) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
23.08 00:34:35 [Server] INFO Caused by: java.lang.NullPointerException
23.08 00:34:35 [Server] INFO at be.isach.ultracosmetics.cosmetics.Cosmetic.getOwnerUniqueId(Cosmetic.java:126) ~[?:?]
23.08 00:34:35 [Server] INFO at be.isach.ultracosmetics.cosmetics.gadgets.Gadget.onPlayerInteract(Gadget.java:361) ~[?:?]
23.08 00:34:35 [Server] INFO at sun.reflect.GeneratedMethodAccessor387.invoke(Unknown Source) ~[?:?]
23.08 00:34:35 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
23.08 00:34:35 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_152]
23.08 00:34:35 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
23.08 00:34:35 [Server] INFO ... 20 more
23.08 00:35:39 [Server] Craft Scheduler Thread - 8/WARN java.lang.NullPointerException
23.08 00:35:39 [Server] Craft Scheduler Thread - 8/WARN at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
23.08 00:35:39 [Server] Craft Scheduler Thread - 8/WARN at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
23.08 00:35:39 [Server] Craft Scheduler Thread - 8/WARN at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
23.08 00:35:39 [Server] Craft Scheduler Thread - 8/WARN at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
23.08 00:35:39 [Server] Craft Scheduler Thread - 8/WARN at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
23.08 00:35:39 [Server] Craft Scheduler Thread - 8/WARN at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
23.08 00:35:39 [Server] Craft Scheduler Thread - 8/WARN at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
23.08 00:35:39 [Server] Craft Scheduler Thread - 8/WARN at java.util.stream.ReferencePipeline.forEach(Unknown Source)
23.08 00:35:39 [Server] Craft Scheduler Thread - 8/WARN at be.isach.ultracosmetics.cosmetics.gadgets.GadgetBatBlaster.onUpdate(GadgetBatBlaster.java:66)
23.08 00:35:39 [Server] Craft Scheduler Thread - 8/WARN at be.isach.ultracosmetics.cosmetics.gadgets.Gadget.run(Gadget.java:142)
23.08 00:35:39 [Server] Craft Scheduler Thread - 8/WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
23.08 00:35:39 [Server] Craft Scheduler Thread - 8/WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
23.08 00:35:39 [Server] Craft Scheduler Thread - 8/WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
23.08 00:35:39 [Server] Craft Scheduler Thread - 8/WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
23.08 00:35:39 [Server] Craft Scheduler Thread - 8/WARN at java.lang.Thread.run(Unknown Source)
23.08 00:36:00 [Server] Craft Scheduler Thread - 16/WARN java.lang.NullPointerException`

I cannot seem to reproduce it with other gadgets..

**Comment by iSach** [comment]
@Waterman1001 Thanks for the detailed explanation.
https://puu.sh/E8pd2/c2764653e8.jar
Does this fix the issue?

**Comment by Waterman1001** [comment]
I can't seem to reproduce it anymore with this version.
Wow! Good job on that :)
I think it is fixed now.
Thank you so much for your help and quick responses and the fact that you really listened to my issue!
Also, really thank you for continuing this plugin again for 1.14.4 etc. :)

**Comment by iSach** [comment]
Thank you for using it! :)
