### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by Zeusox** [iSach/UltraCosmetics#445]
### What happened? 
Upgrade from version 2.4.11 to version 2.5 and some cosmetics do not work in 1.8, such as morphs, pets or effects, others do
### What version of UltraCosmetics are you using?  
2.5
### What Spigot version are you using? Paste the output of /version below.  
1.8.8
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
https://paste.helpch.at/liyuyisido.pl
### Any additional information that you would like to provide that may be relevant to the issue?
In version 2.4.11 everything works except the morphs in the third person view

**Comment by iSach** [comment]
Can you send your config please?

**Comment by Zeusox** [comment]
I translated it into Spanish
Config:
https://paste.helpch.at/xalivijuvo.php
Messages:
https://paste.helpch.at/zaxozafafo.sql

**Comment by iSach** [comment]
Thank you.

Can you please try again with 2.5.1

**Comment by Zeusox** [comment]
It works, thanks you c:
