### ISSUE TITLE
Treasure Chests cant be opened in Non-OP Mode/Survival on 1.14.4 Server (Spigot)

### ISSUE THREAD

**Issue by derFuxi** [iSach/UltraCosmetics#446]
### What steps will reproduce the issue?  
1. Deop and give permissions to use the GUI
2. Buy a key 
3. Stand on Land and try to open the Treasure Chest

### What happened? 
I gut stuck on the Block and the chest arent visible but there is something invisible around me
### What version of UltraCosmetics are you using?  
The newest
### What Spigot version are you using? Paste the output of /version below.  
1.14.4
### What plugins do you have installed? Paste the output of /plugins below.  
GriefPrevention
SpawnX
PEX
Vault
Iconomy3
Dtl Shop Plugin
WorldEdit
Citizen2
Chairs
Dynmap
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
NO Errors in Console
```
### Any additional information that you would like to provide that may be relevant to the issue?
Its working with OP-Rights but not without OP-Rights

**Comment by iSach** [comment]
Land is from "GriefPrevention" plugin?

What kind of flags are there on that land?

**Comment by derFuxi** [comment]
There are no flags on that Land normally, i didnt claimed it, there are only Flags on protected Land but there is nothing protected

**Comment by derFuxi** [comment]
If you want to test it join with 1.14.4 on the Server IP: derfuxi1.pizza and buy 1 Key and try to open the Chest

**Comment by iSach** [comment]
I'm coming soon.

**Comment by derFuxi** [comment]
You can come online every time to test it, i cleared 2 areas to test the Treasure Chests
when i remove the GriefPrevention Plugin it isnt working too

**Comment by derFuxi** [comment]
when i delete all Plugins, its still the same Error

**Comment by derFuxi** [comment]
Everything works well in Version 2.5.2
