### ISSUE TITLE
FAQ page of wiki is outdated.

### ISSUE THREAD

**Issue by Andre601** [iSach/UltraCosmetics#447]
[FAQ]: https://github.com/iSach/UltraCosmetics/wiki/Frequently-Asked-Questions

This is not directly related to UC, but the [FAQ] page on the wiki is outdated. The first question still has the answer that UC works on 1.8 up to 1.12 while it now supports 1.13 and 1.14 so an update would be good.

**Comment by iSach** [comment]
Thanks for letting me now! I've fixed it.
