### ISSUE TITLE
People don't die when falling in the void and riding a mount

### ISSUE THREAD

**Issue by Waterman1001** [iSach/UltraCosmetics#448]
### What steps will reproduce the issue?  
1. Ride a mount
2. Fall into the void
3. Don't die

### What was supposed to happen?
Players are supposed to die, since otherwise they can keep on loading chunks and fall forever while riding a mount in the void.

### What happened?
Players did not die when riding on a mount.

### What version of UltraCosmetics are you using?
2.5.2  

### What Spigot version are you using? Paste the output of /version below.  
CraftBukkit version git-Spigot-798ea6a-368f4e9 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
No

### Any additional information that you would like to provide that may be relevant to the issue?
Not really, I just was hoping that people somehow can maybe get their mount disabled as soon as they reach for example y=-20 or something, such that they just die in the void.
Otherwise they can just go AFK and keep falling in the void and load chunks and fall untill they reach like y=-900000 :p 

Thank you so much for understanding my issue and your help :)

**Comment by iSach** [comment]
Fixed in e47788e
https://puu.sh/E9n9V/79aac35d81.jar
Download the pre-release ^^^
