### ISSUE TITLE
Mounts go way too fast and make player invulnerable

### ISSUE THREAD

**Issue by s1h4d0w** [iSach/UltraCosmetics#451]
### What steps will reproduce the issue?  
1. Use a mount like the Drugged Horse
2. Ride it
3. Mount is waaaay too fast and makes you invulnerable
4. After you get off the nausea effect isn't removed

### What was supposed to happen?
- The mount having a fast but reasonably normal speed, now chunks aren't even loading in because players are so fast
- The mount not making you invulnerable to damage
- The nausea being removed when unmounting

### What happened? 
- See above

### What version of UltraCosmetics are you using?  
2.5.4

### What Spigot version are you using? Paste the output of /version below.  
Paper version git-Paper-176 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### What plugins do you have installed? Paste the output of /plugins below.  
AntiCurse, ArmoredElytra*, AuthMe, AutoMessager, BetterRTP*, ChatReaction, ChopTree2, ClearLag, CoreProtect, CrazyEnchantments, DeathCoordinates, DynamicShop, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, GriefPrevention, HolographicDisplays, InfernalMobs, Item2Chat, Jobs, JoinMessagePlus*, JukeBox, KeepDeathDrop*, LuckPerms, Matrix, MineableSpawners, Multiverse-Core, MyCommand, NoteBlockAPI, OnTime*, PhantomSMP, ProtocolLib, QuickShop, ServerListPlus*, SkinsRestorer, StackMob, SuperbVote, UltraCosmetics, Vault, Votifier, WorldBorder, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags  

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
none
```

**Comment by iSach** [comment]
It's supposed to be like that.

Ultra Cosmetics shouldn't be used in a survival context.

**Comment by s1h4d0w** [comment]
Thanks, forgot to close this after we chatted on Discord, my username there is "lepel".
