### ISSUE TITLE
broken explosive sheep

### ISSUE THREAD

**Issue by offcalster** [iSach/UltraCosmetics#452]
### What steps will reproduce the issue?  
1.  idk i dont code
2.  idk i dont code
3.  idk i dont code

### Any additional information that you would like to provide that may be relevant to the issue? no extra info but i will give a screenshot if thats possible here also i love the plugin also i think you should make some sort of rainbow gadget or particle effect that would be cool

![2019-09-04_19 39 29](https://user-images.githubusercontent.com/54910567/64281845-f451a900-cf4b-11e9-86f4-3f925ff9496d.png)
![2019-09-04_19 39 37](https://user-images.githubusercontent.com/54910567/64281846-f451a900-cf4b-11e9-9572-fd7da46d5c19.png)

**Comment by datatags** [comment]
Explosive sheep works fine now, maybe it was fixed at some point?
