### ISSUE TITLE
Items dropped on ground

### ISSUE THREAD

**Issue by necsurv** [iSach/UltraCosmetics#454]
### What steps will reproduce the issue?  
1. Put any cosmetic suit on
2. All of the items that you had on drop on the ground
3. If your inventory is full other people can get them

### What was supposed to happen?
Probably should have a force slot to be empty to equip some how in the code
### What happened? 
Items on the ground
### What version of UltraCosmetics are you using?  
2.5.5?

**Comment by iSach** [comment]
I will add an option for that later.
Currently, it drops to avoid deleting the item.
What do you prefer:
- Not equip and say a message "you need to empty the slot"
- Make the slot unusable for any item.
