### ISSUE TITLE
Permissions of Astronaut Suit seem to not work properly

### ISSUE THREAD

**Issue by Waterman1001** [iSach/UltraCosmetics#456]
### What steps will reproduce the issue?  
1. Add permission ultracosmetics.suits.astronaut.chestplate to someone
2. Player does not have permission to the chestplate
3. Add permission ultracosmetics.suits.astronaut.helmet to someone
4. Player suddenly has permission to chestplate. But NOT to the helmet..
5. This also holds for leggings and boots.

### What version of UltraCosmetics are you using?  
2.5.5

### What Spigot version are you using? Paste the output of /version below.  
CraftBukkit version git-Spigot-065a373-763e560 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by iSach** [comment]
Can't reproduce on my side. What permission plugins are you using? LuckPerms works on my side.

**Comment by Waterman1001** [comment]
Oh really? Hmm that's strange.
I am using PermissionsEx (I know this is kind of outdated, but it seems to work still fine)
Thanks for your reply.
Also, when testing I deopped myself.

**Comment by iSach** [comment]
I deopped myself too. And it looked like it works. I can’t test with PEX right now but it’s a weird mistake.

**Comment by datatags** [comment]
Can't reproduce with LuckPerms, sounds like there's a delay or queue on permission updates that's causing issues.
