### ISSUE TITLE
Automatic move when morphed

### ISSUE THREAD

**Issue by Elric02** [iSach/UltraCosmetics#458]
### What steps will reproduce the issue?  
1. use a morph (whatever it is)
2. press a directional key (move forward, backward, left or right), no need to keep the key pressed
3. you will now automatically move slowly in this direction
4. press a directional key (move forward, backward, left or right), no need to keep the key pressed
5. you will now automatically move slowly in this direction

### What was supposed to happen?
You shouldn't move if you're not pressing the key anymore...

### What version of UltraCosmetics are you using?  
2.5.5

### What Spigot version are you using? Paste the output of /version below.  
This server is running CraftBukkit version git-Spigot-da42974-8f47214 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

### What plugins do you have installed? Paste the output of /plugins below.  
PlaceholderAPI, NametagEdit, EntityDetection, WooMinecraft, ViaVersion, BuycraftX, Multiverse-Core, LibsDisguises, PermissionsEx, MyCommand, Essentials, UltraCosmetics

**Comment by datatags** [comment]
This is an issue with LibsDisguises, it should be disabling collision for the disguise. It doesn't happen if you turn off "morphs third person view" in the GUI though.
