### ISSUE TITLE
Slime and Spider mounts

### ISSUE THREAD

**Issue by Elric02** [iSach/UltraCosmetics#459]
### What steps will reproduce the issue?  
1. Mount a Slime or a Spider

### What happened? 
Slime and Spider don't show up, but are still counted as if they were spawned normally, if you sneak you come back to where you were and it says they are despawned

### What version of UltraCosmetics are you using?
2.5.5

### What Spigot version are you using? Paste the output of /version below.
This server is running CraftBukkit version git-Spigot-da42974-8f47214 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

### What plugins do you have installed? Paste the output of /plugins below.
PlaceholderAPI, NametagEdit, EntityDetection, WooMinecraft, ViaVersion, BuycraftX, Multiverse-Core, LibsDisguises, PermissionsEx, MyCommand, Essentials, UltraCosmetics

**Comment by iSach** [comment]
Is your world in peaceful difficulty?

**Comment by Elric02** [comment]
No, I'm not in peaceful.

But works fine with latest version (2.5.7) in 1.15.1, I'm closing the issue
