### ISSUE TITLE
config.yml repeating commented lines

### ISSUE THREAD

**Issue by SlayG** [iSach/UltraCosmetics#46]
Not exactly sure how to replicate this issue, but it isn't the first time it's happened.

[Here is an example of what is going on](http://pastebin.com/UMcGkahZ)

Mind you, I had to cut this by about 80% because the file was literally too large to process through either pastebin or online-yamlparser. Just the same commented lines repeating endlessly. At least a few ten-thousand lines.

It should also be noted that this is causing the plugin to "hang" the entire startup sequence, due to having to skim through multiple thousands of lines in the configuration file to find the actual values within.

I apologize if this is not enough information, I will give more if I can/need to. 

Plugin version is 2.0.5, as of this posting I am updating to 2.0.6 to see if the issue persists.

**Comment by JHXSMatthew** [comment]
Should be fixed in 2.0.6.
