### ISSUE TITLE
Glow Feature

### ISSUE THREAD

**Issue by cwchristerw** [iSach/UltraCosmetics#466]
![2019-12-12_13 23 09](https://user-images.githubusercontent.com/13464896/70708352-f497d800-1ce2-11ea-96d5-ffd2d272224a.png)

This could use PlaceHolderAPI to change color of name and in that way it will change color of glow :)
![2019-12-12_13 29 55](https://user-images.githubusercontent.com/13464896/70708575-856eb380-1ce3-11ea-8643-08ab1c0a17a2.png)

Here is plugin that does this but it causes my TAB plugin to fail group priority and there for Citizens 2 NPC are on top of all players and not below them: https://www.spigotmc.org/resources/eglow-1-9-4-1-14-x-glow-cosmetic-respects-eula-mysql-support.63295/

![2019-12-12_13 28 49](https://user-images.githubusercontent.com/13464896/70708505-58ba9c00-1ce3-11ea-9013-e1ab8a0fa1b9.png)

**Comment by datatags** [comment]
Since this would require a new category of cosmetics which I don't think UC is ready for at the moment, and since there's already a plugin that does it fairly well, I'll close this for now.
