### ISSUE TITLE
MountOfWater and EnderDragon not always despawning

### ISSUE THREAD

**Issue by Elric02** [iSach/UltraCosmetics#468]
### What steps will reproduce the issue?  
1. Spawn MountOfWater or EnderDragon
2. dismount it

### What was supposed to happen?
It should despawn.

### What happened? 
Doesn't despawn everytime, sometimes it just keeps there and becomes a classic renamed horse, but invincible. No particles anymore when mounting it though.
When reloading plugin,the horse isn't invincible anymore.
Same goes for EnderDragon

### What version of UltraCosmetics are you using?
2.5.7

### What Spigot version are you using? Paste the output of /version below.  
Paper version 60, 1.15.1

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
No log in the console

**Comment by Elric02** [comment]
Edit : same bug goes for EnderDragon

**Comment by datatags** [comment]
Can't reproduce with water mount, ender dragon mount was disabled at some point. Please re-open if this is still an issue on latest UC.
