### ISSUE TITLE
molten snake

### ISSUE THREAD

**Issue by BiggDaddyy** [iSach/UltraCosmetics#469]
### What steps will reproduce the issue?  
1. https://cdn.discordapp.com/attachments/185055040036143104/675709450014818304/javaw_jBbEsH0eoT.png
2. Molten Snake looks like the picture on 1. xD

### What was supposed to happen?
there should be a molten snake? xD
### What happened? 
you can see it on the picture xD
### What version of UltraCosmetics are you using?  
2.5.7
### What Spigot version are you using? Paste the output of /version below.  
paper 1.15.2
### What plugins do you have installed? Paste the output of /plugins below.  
https://pastebin.com/4hd1GQ5P
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
i get this error now and then but else no error when the snake is used
https://pastebin.com/2AxQRQFU
```
### Any additional information that you would like to provide that may be relevant to the issue?
![2](https://user-images.githubusercontent.com/20758605/74088036-3dc19980-4a92-11ea-9f3a-7993b1f74d73.png)
![unknown](https://user-images.githubusercontent.com/20758605/74088038-3ef2c680-4a92-11ea-82ac-368525b536d9.png)

**Comment by datatags** [comment]
Can't reproduce. Since this is an old issue I doubt it's still a problem, but if it is, please re-open with current info on it and I'll take a look.
