### ISSUE TITLE
Molten Snake issues

### ISSUE THREAD

**Issue by Elric02** [iSach/UltraCosmetics#470]
### What steps will reproduce the issue?  
1. summon Molten Snake

### What happened? 
Many logs on console, and huge server lag (not sure if it's related)

### What version of UltraCosmetics are you using?  
2.5.7

### What Spigot version are you using?
1.15.1, Paper 60

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
https://pastebin.com/YtAmMbPE

**Comment by datatags** [comment]
Looks like this has probably been fixed, please re-open if it's still a problem.
