### ISSUE TITLE
Setting "Pets-Drop-Items" to false makes the Wither pet an adult and shoot things

### ISSUE THREAD

**Issue by I-Knight-I** [iSach/UltraCosmetics#471]
### What steps will reproduce the issue?  
1. Pets-Drop-Items: false | Pets-Are-Babies: true
2. Reload
3. Spawn Wither pet

### What was supposed to happen?
Wither should be small (like normal) or at least shouldn't shoot things.

### What happened? 
Wither was an adult and shot things, damaging terrain and mobs.

### What version of UltraCosmetics are you using?  
2.5.7

### What Spigot version are you using? Paste the output of /version below.  
Paper Build 103 (Minecraft 1.15)

### What plugins do you have installed? Paste the output of /plugins below.  
66 plugins. 99.9% sure this isn't related to them though.

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
N/A
```
### Any additional information that you would like to provide that may be relevant to the issue?
Preventing the Wither from shooting would be an acceptable change but the fix by making the Wither become an adult when affected only by "Pets-Are-Babies" is needed.

**Comment by datatags** [comment]
Fixed in dev builds. Wither pet also now respects the Pets-Are-Babies setting. Thanks for the report! 🙂
