### ISSUE TITLE
[Suggestion] Chest GUI treasurechests

### ISSUE THREAD

**Issue by TheRobLP** [iSach/UltraCosmetics#472]
I think it would be nice if there was an optional mode for treasure chests where you would get a GUI upon klicking a block which is predefined by server Admins. Reason for this proposition is, that when you want to make a centralized way for players to access treasure chests they would piel up on the same spot when executing the command. With a GUI every player would have his own form instead of being teleported to the same place, which could cause issues.

**Comment by datatags** [comment]
I'm not really clear on what you're wanting, it sounds like #567 but the opposite? Since it's so old I'm gonna close it, but if you can clarify please re-open it :)
