### ISSUE TITLE
Disco Ball gadget giving NPE due to searching for players after disco ball deleted

### ISSUE THREAD

**Issue by dode5656** [iSach/UltraCosmetics#479]
### What steps will reproduce the issue?  
1. Use the Disco Ball gadget
2. Wait till it finishes

### What was supposed to happen?
To end the disco ball gadget with no errors

### What happened? 
It gave an NPE error due to it not finding the players beside the disco ball after the disco ball has been removed

### What version of UltraCosmetics are you using?  
Latest 2.5.7

### What Spigot version are you using? Paste the output of /version below.  
```
[14:17:32 INFO]: This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[14:17:32 INFO]: Previous version: git-Paper-653 (MC: 1.13.2)
[14:17:32 INFO]: Checking version, please wait...
[14:17:33 INFO]: You are running the latest version
```

### What plugins do you have installed? Paste the output of /plugins below.  
Issue not related to other plugins

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
https://hastebin.com/ruxiqozoku.md

### Any additional information that you would like to provide that may be relevant to the issue?
as said in what happened i think its caused by the plugin not finding players beside the disco ball after the disco ball has been removed/deleted

**Comment by datatags** [comment]
Seems like it's been fixed. Hard to tell since the paste expired or something.
