### ISSUE TITLE
Everytimes I edit permissions.yml , It say " permissions.yml empty" and recreate a new one with default settings

### ISSUE THREAD

**Issue by Chatthon** [iSach/UltraCosmetics#480]
### What steps will reproduce the issue?  
1. Edit permissions.yml
2. start the server

### What was supposed to happen?
It should keep my settings on permissions.yml
### What happened? 
the settings of permissions.yml are set back to default
### What version of UltraCosmetics are you using?  
UltraCosmetics v2.5.7
### What Spigot version are you using? Paste the output of /version below.  
CraftBukkit version git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
### What plugins do you have installed? Paste the output of /plugins below.  

Fichier
plugins
67
__MACOSX
ActionHealth
bStats
BuildBattle
Carz
ChairStairs
Citizens
CommandNPC
CrackShot
CraftmotoLite
CustomHeads
EasyCarts
LuckyBlock
MCLib
MGBedWars
MGConquer
MGGungame
MGMobEscape
MGSkyWars
MinigamesLib
MultiWorld
OpenAudioMc
PixelPrinter
PixelPrinter.jar
PluginMetrics
Sentry
SerialKey
Ships
Skyupdater
SuperLobbyPlus
UltraCosmetics
Updater
Vault
WorldEdit
WorldGuard
### Any additional information that you would like to provide that may be relevant to the issue?
> [19:49:46 INFO]: Server permissions file permissions.yml is empty, ignoring it
> [19:49:48 INFO]: Done (83.805s)! For help, type "help" or "?"
and sorry i'm French, I hope you still understand :)

**Comment by Permanently** [comment]
How does this have anything to do with UltraCosmetics?

**Comment by datatags** [comment]
Not related to UltraCosmetics.
