### ISSUE TITLE
SmashDown Gadget Bug?

### ISSUE THREAD

**Issue by xoTomm** [iSach/UltraCosmetics#484]
### What steps will reproduce the issue?  
1. Using the Smashdown Gadget.
2. 
3. 

### What was supposed to happen?
player is meant to use the gadget to launch in the air and create a small ripple when they hit the ground.
### What happened? 
The SmashDown Gadget works, but when the player hits the ground it causes a huge wave of blocks to raise from the ground in a circle, damaging the terrain and continuing to move throughout the world unless the server is stopped.
### What version of UltraCosmetics are you using?  
2.5.7
### What Spigot version are you using? Paste the output of /version below.  
This server is running Paper version git-Paper-77 (MC: 1.15.2)
### What plugins do you have installed? Paste the output of /plugins below.  
plugins (61): AuctionHouse, Betterinvsee, BuycraftX, Chairs, ChatControl, ChatFeelings, ChestShop, ChunkBuster, Citizens, ClearLag, CoreProtect, CrazyCrates, CreativeItemControl, DeadChest, Denizen, DiceFurniture, DiscoFloor*, DiscordPlugin*, EditableSign, Elevators_v2, Essentials, EssentialsChat, EssentialsSpawn, Factions, FastAsyncWorldEdit, FurnitureLib, GriefPrevention, HolographicDisplays, HubBasics, Lottery, MarriageMaster, Minepacks, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MyPet, NoteBlockAPI, ObyBreaker, OreAnnouncer, PermissionsEx*, PlaceholderAPI, PlotSquared, PluginConstructorAPI, ProtectionLib*, ProtocolLib, pvparena, PvPManager, SellWands*, ServerSigns, Shopkeepers, SpawnerSilk, Suggestions*, TitleManager, UltraCosmetics, Vault, VoidSpawn, Wild, WorldBorder*, WorldEdit, WorldGuard, WorldGuardExtraFlags
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
-
```
### Any additional information that you would like to provide that may be relevant to the issue?
Here is a screenshot of the issue in question: https://imgur.com/a/DkpdWIC

**Comment by datatags** [comment]
Can't reproduce, hopefully fixed at some point.
