### ISSUE TITLE
Dying causes Hats and Emotes to drop

### ISSUE THREAD

**Issue by JewishBagel** [iSach/UltraCosmetics#486]
### What steps will reproduce the issue?  
1. Have a pvp mod installed
2. Get a friend
3. have them kill you or use /suicide

### What was supposed to happen?
The heads wont drop along with items, same with emotes.
### What happened? 
The heads will drop along with items, same with emotes.
### What version of UltraCosmetics are you using?  
2.5.7
### What Spigot version are you using? Paste the output of /version below.  
Paper 1.15.2
### What plugins do you have installed? Paste the output of /plugins below.  
https://gyazo.com/dc6f4b1a9980923d85ae392215025a1a
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
None

**Comment by datatags** [comment]
Guess this was fixed at some point.
