### ISSUE TITLE
cannot move items into chests/crafting slots with number keys

### ISSUE THREAD

**Issue by TheBurningBacca** [iSach/UltraCosmetics#488]
### What steps will reproduce the issue?  
1. open a chest or crafting table
2. move mouse curser over any slot in chest/crafting table/etc.
3. press any number key that contains an item on your hotbar (1-9)

### What was supposed to happen?
The item should have gone into the chest or crafting table
### What happened? 
The item did not go into the chest or crafting table
### What version of UltraCosmetics are you using?  
UltraCosmetics-2.5.7-RELEASE.jar
### What Spigot version are you using? Paste the output of /version below.  
This server is running Paper version git-Paper-245 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
### What plugins do you have installed? Paste the output of /plugins below.  
this is irrelevant because i have replicated this with only UltraCosmetics running, and then with no plugins it is gone. https://pastebin.com/NvtGPhBT
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
there are no errors that i could see
```
### Any additional information that you would like to provide that may be relevant to the issue?

I think this was put in intentionally due to this plugin primarily being intended as a fun hub plugin, and I think there should simply be an option in the config or somewhere to disable this. Also I have seen this plugin on another survival server and they had the exact same issue. Maybe not many other people know of this because most people craft or put things into chests by dragging and dropping, idk

**Comment by datatags** [comment]
Same as #499, which was resolved.
