### ISSUE TITLE
OnDisable Error

### ISSUE THREAD

**Issue by DevJorgeMCS** [iSach/UltraCosmetics#490]
### What steps will reproduce the issue?  
1. Just stop or reload the server

### What was supposed to happen?
Don't show error (?

### What happened? 
Console error, doest'n affect (i guess). 

### What version of UltraCosmetics are you using?  
2.5.7

### What Spigot version are you using? Paste the output of /version below.  

This server is running Paper version git-Paper-309 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### What plugins do you have installed? Paste the output of /plugins below.  

Plugins (36): AdvancedBan*, AsyncWorldEdit, AuctionHouse, BossShopPro, BountyHunters, ChatManager, CleanMotD*, CrazyCrates, Essentials, EssentialsChat, EssentialsSpawn, HolographicDisplays, HolographicExtension, ItemShops*, LibsDisguises, LuckPerms, MineResetLite, MoneyPouch*, MoneyPrinters, Multiverse-Core, PlaceholderAPI, PlayerKits, PlayerShops, ProtocolLib, PunishmentGUI*, SimpleScore, TAB, TradeSystem, UltraCosmetics, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  

onDisable error: https://pastebin.com/72XZHhHV

**Comment by datatags** [comment]
Partially fixed a while back, fully fixed in dev builds which are found in the Discord.
