### ISSUE TITLE
Corner stairs don't revert back to normal ones after using something that changes blocks.

### ISSUE THREAD

**Issue by RudRecciah** [iSach/UltraCosmetics#491]
### What steps will reproduce the issue?  
1. Activate any cosmetic that changes blocks, for example horses or freeze cannon
2. Use the cosmetic on either an outside or inside corner stair
3. Watch the stair turn into a normal stair instead of a corner one when it reverts back to normal.

### What was supposed to happen?
The stair was supposed to turn back into a corner stair.
### What happened? 
The stair reverted to a normal stair instead of a corner one.
### What version of UltraCosmetics are you using?  
2.5.7
### What Spigot version are you using? Paste the output of /version below.  
Paper version git-Paper-194 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
### What plugins do you have installed? Paste the output of /plugins below.  
CommandRegions*, DeluxeMenus, HolographicDisplays, ItemJoin, LibsDisguises, MEP, NoHunger*, PlaceholderAPI, ProtocolLib, UltraCosmetics, WorldEdit, WorldGuard
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
n/a
### Any additional information that you would like to provide that may be relevant to the issue?
n/a

**Comment by srnyx** [comment]
Happening to me too. @iSach please fix.

Except:
* Any type of stairs/slabs will glitch out (become ghost blocks for the player) when a mount that changes blocks changes them.
* Stairs/slabs will be removed (on both client and server) when a treasure chest design is used when standing on top of them.

**Comment by RudRecciah** [comment]
damn this hasn't been fixed yet?

**Comment by srnyx** [comment]
> damn this hasn't been fixed yet?

Recommend switching to another cosmetics plugin.
This plugin has more than just this 1 game-breaking issue.

* Insane lag spikes when using certain gadgets (i.e. Thor's Hammer)
* Stairs/slabs are deleted when opening boxes/riding mounts
* Not very customizable
* And all the other **90** issues on this GitHub (there are some things from **2016** still)

**Comment by RudRecciah** [comment]
> > damn this hasn't been fixed yet?
> 
> Recommend switching to another cosmetics plugin.
> This plugin has more than just this 1 game-breaking issue.
> 
> * Insane lag spikes when using certain gadgets (i.e. Thor's Hammer)
> * Stairs/slabs are deleted when opening boxes/riding mounts
> * Not very customizable
> * And all the other **90** issues on this GitHub (there are some things from **2016** still)
> * Last commit was more than a month ago (July 31)
> * Discord server is completely dead

oof
i havent been using cosmetic plugins for basically as long as this issues been up so i never knew it died
it sucks that development didnt continue, this used to be my favorite cosmetics plugin

**Comment by iSach** [comment]
> > damn this hasn't been fixed yet?
> 
> 
> 
> Recommend switching to another cosmetics plugin.
> 
> This plugin has more than just this 1 game-breaking issue.
> 
> 
> 
> * Insane lag spikes when using certain gadgets (i.e. Thor's Hammer)
> 
> * Stairs/slabs are deleted when opening boxes/riding mounts
> 
> * Not very customizable
> 
> * And all the other **90** issues on this GitHub (there are some things from **2016** still)
> 
> * Last commit was more than a month ago (July 31)
> 
> * Discord server is completely dead

Damn! A free and open source plugin has not fixed every mentioned issue!

If you want so much an issue to be fixed, contribute to the project.

I have worked quite a lot of time on this project (probably hundreds of hours), I’ve never got anything from it. I don’t have time to contribute to it anymore, because of a job, and studies. 

People are free to contribute, but very few actually do, more prefer to complain, like you. The principle of free software is for people to help and contribute, to make great software accessible.

I can't even believe you dare complain about last commit being one month ago lol
