### ISSUE TITLE
Inventory is openig and directly closing

### ISSUE THREAD

**Issue by NiclasM13** [iSach/UltraCosmetics#495]
### What steps will reproduce the issue?  
1. Open the Inventory

### What was supposed to happen?
Open the Inventory
### What happened? 
It closed directly
### What version of UltraCosmetics are you using?  
The newest
### What Spigot version are you using? Paste the output of /version below.  

[08:32:04 INFO]: This server is running Paper version git-Paper-322 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[08:32:04 INFO]: Checking version, please wait...
[08:32:04 INFO]: Previous version: git-Paper-226 (MC: 1.15.2)
[08:32:04 INFO]: You are 24 version(s) behind

### What plugins do you have installed? Paste the output of /plugins below.  

 ajParkour, AutoMessage, ChestShop, ColoredAnvils*, CPCameraStudioReborn*, DiscordSRV, Essentials, EssentialsChat, EssentialsProtect, GSit, HolographicDisplays, HolographicExtension, Lobby*, LobbySecrets*, LuckPerms, Multiverse-Core, Multiverse-Portals, MysqlEcoBridge*, PlaceholderAPI, PlotSquared, PlugMan, ProfessionalBans_Reloaded_Anticheat, ProtocolLib, SimplePortals, SuperVanish, TAB, TouchscreenHolograms, UltimateTimber, UltraCosmetics, Vault, WitherAC, WorldEdit, WorldGuard

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
```

**Comment by datatags** [comment]
Can't reproduce even on Paper 1.15.2, please re-open with your actual UC version and current MC version if it's still a problem.
