### ISSUE TITLE
Morph world switch bug

### ISSUE THREAD

**Issue by Bbro122** [iSach/UltraCosmetics#496]
### What steps will reproduce the issue?  
1.  Pick a morph
2.  Switch to a cosmetic disabled world
### What was supposed to happen?
       Cosmetic shouldve properly been disabled
### What happened? 
      Cosmetic remains enabled and you have the morph abilities
### What version of UltraCosmetics are you using?  
        2.5.7
### What Spigot version are you using? Paste the output of /version below.  
       Paper version git-Paper-192 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
### What plugins do you have installed? Paste the output of /plugins below.  
        Plugins (48): AdvancedBan, BanAnnouncer, BannerMaker, BetterChairs, BuyPlots, Carz, ChatInjector, ChatManager, Citizens, CoreProtect, CreativeGates, DiscordSRV, Essentials, Hat, JukeBox, LibsDisguises, LightAPI, LuckPerms, Marriage, MassiveCore, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, MusicBox, MyCommand, NametagEdit, NoteBlockAPI, PixelPrinter, PlaceholderAPI, PlotSquared, PluginConstructorAPI, PlugMan, PremiumVanish, ProtocolLib, PunishmentGUI, QualityArmory, QualityArmoryVehicles, RPNames, Sentinel, Spicord, StayPut*, SuperLobby, UltraCosmetics, Vault, Votifier, VotingPlugin, WorldEdit, WorldGuard
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
paste
error(s)
here
```

**Comment by datatags** [comment]
Same as #537, which was fixed.
