### ISSUE TITLE
Why do you cancel every InventoryClickEvent?

### ISSUE THREAD

**Issue by mfnalex** [iSach/UltraCosmetics#499]
```java
if ((event.getCurrentItem() == null || event.getCurrentItem().getType() == Material.AIR)
                    && (event.getCursor() == null || event.getCursor().getType() == Material.AIR)) {
                event.setCancelled(true);
```

Why the hell do you cancel every InventoryClickEvent that is called when someone clicks an empty slot?
https://github.com/iSach/UltraCosmetics/blob/master/core/src/main/java/be/isach/ultracosmetics/listeners/PlayerListener.java#L165

This is a really dealbreaker for my mechanism that detects custom gui inventories by third party plugins.

**Comment by iSach** [comment]
It must be there to prevent users from placing items in the inventory.

**Comment by mfnalex** [comment]
in what inventory? cant you check if the affected inventory belongs to your plugin? This blocks ALL clicks in the Player's inventory.

**Comment by mfnalex** [comment]
```16.07 18:39:34 [Server] INFO ============== EVENT CANCELLED ==============
16.07 18:39:34 [Server] INFO Event: InventoryClickEvent
16.07 18:39:34 [Server] INFO Class: org.bukkit.event.inventory.InventoryClickEvent
16.07 18:39:34 [Server] INFO has been cancelled by
16.07 18:39:34 [Server] INFO Plugin: UltraCosmetics
16.07 18:39:34 [Server] INFO Class: be.isach.ultracosmetics.UltraCosmetics
16.07 18:39:34 [Server] INFO =============================================
```

This was a regular InventoryClickEvent on a normal PlayerInventory. :/

```16.07 18:28:18 [Server] INFO InventoryClickEvent:
16.07 18:28:18 [Server] INFO - Holder: CraftPlayer{name=AcesGamingUK}
16.07 18:28:18 [Server] INFO - Holder class: class org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer
16.07 18:28:18 [Server] INFO - Slot: 9
16.07 18:28:18 [Server] INFO - Left-Click: false
16.07 18:28:18 [Server] INFO - Right-Click: true
16.07 18:28:18 [Server] INFO - Shift-Click: false```

**Comment by mfnalex** [comment]
Also, why do you "must" cancel a click into an empty slot? If the slot is empty and the hand is empty too, nothing would ever happen

**Comment by iSach** [comment]
Oh, it's not to prevent placing items into the inventory. It's to prevent players from moving the chest in their inventory. Might be a workaround for some inventory issues or spams that players could use to bypass the protection and move the gadget item in their inventory, I'll have a look to remove that and see why it was added. I don't remember currently.

**Comment by mfnalex** [comment]
It would be awesome if you could do it some other way, because I am currently trying to detect whether inventories belong to a GUI by spawning a fake InventoryClickEvent and check if that gets cancelled

**Comment by AcesGamingUK** [comment]
i also am having this issue
`It's to prevent players from moving the chest in their inventory.`
But I don't even have that enabled for it to trigger?
```
Menu-Item:
  Give-On-Join: false <<<<<
  Give-On-Respawn: false <<<<
  Slot: 3
  Type: ENDER_CHEST
  Data: 0
  Displayname: '&6&lCosmetics'
```

**Comment by iSach** [comment]
> It would be awesome if you could do it some other way, because I am currently trying to detect whether inventories belong to a GUI by spawning a fake InventoryClickEvent and check if that gets cancelled. It worked fine so far with all other plugins that have been tested and we really could not find what plugin blocked that event, so I had to also tinker that EventLogger together^^
> 
> Can't you just check if the inventory belongs to your plugin? Or use a custom inventoryholder by which you can identify your inventories?

I will have a look when possible. Thanks for telling me. This part of the code is 4 years old, there must be a reason behind it, but it's not a good one.



> i also am having this issue
> `It's to prevent players from moving the chest in their inventory.`
> But I don't even have that enabled for it to trigger?
> 
> ```
> Menu-Item:
>   Give-On-Join: false <<<<<
>   Give-On-Respawn: false <<<<
>   Slot: 3
>   Type: ENDER_CHEST
>   Data: 0
>   Displayname: '&6&lCosmetics'
> ```

These options were probably not there yet when that code was added, and it has not been modified since 2016. I will fix that.

**Comment by mfnalex** [comment]
Thank you 👍
