### ISSUE TITLE
Nyan Mount Error

### ISSUE THREAD

**Issue by rocky143** [iSach/UltraCosmetics#5]
Getting this error on trying to enable http://pastebin.com/kphD6SYh

**Comment by iSach** [comment]
Do you have PermissionsEx for the permissions or another permissions plugin? What Spigot version?

**Comment by rocky143** [comment]
Latest spigot 1.8.8.
And yes, I do use pex.

**Comment by iSach** [comment]
Mmh really weird this shouldn't happen I don't understand. Can I see the config and messages?

**Comment by iSach** [comment]
Sorry failed, not closed

**Comment by rocky143** [comment]
This issue has not been fixed http://pastebin.com/KKQdrSZy
Its also happening to Blizzard Blast Gadget, prints the same error.

**Comment by iSach** [comment]
Does it happen with default config and messages?

No, using Java 8 on a server makes your server compatible with all the plugins compiled with Java 8 or less. It's if I had made my plugin with Java 8 that users with Java 7, or 6 would have problems. So on a server it's always good to use the latest Java version.

**Comment by rocky143** [comment]
I found the issue, you named the names too long for both it was cutting off which is why it was not working. And yes, I am talking about default config.
It goes something like this: &b&lSpawn &4&lNy&6&la&e&ln &a&lSh&b&lee&d&lp 
and 
&b&lActivate &b&lBlizzard Blaster
I changed the names and its working now, you might want to change the default config.

**Comment by iSach** [comment]
Works perfectly for me

**Comment by iSach** [comment]
Don't you think every mount and other is tested?

**Comment by rocky143** [comment]
Weird, I loaded it up and it wasn't working for me.
Might be something blocking it. Anyhow, thanks for the help.
