### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ondra2305** [iSach/UltraCosmetics#50]
**Hey,
I have problem with you plugin UltraCosmetics. When i click on something (morph, pet...) it will say: You equiped and 1 second after: You unequiped... I have RIGHT version of Spigot (1.8.8) and Java (8)! Can you help me?** @iSach
_ondra2305_
![vystrizek](https://cloud.githubusercontent.com/assets/17100366/12868211/12894996-cd02-11e5-8de7-bac583acb33a.PNG)
![vystrizek2](https://cloud.githubusercontent.com/assets/17100366/12868223/694290ee-cd02-11e5-9002-e3fde48bf492.PNG)

**Comment by JHXSMatthew** [comment]
Uhm, did you enable creature spawn in that world ?

**Comment by ondra2305** [comment]
If there is a problem here, only pets and morphs will not work, for me isnt working anything.
But thank you for reply ;)

**Comment by ondra2305** [comment]
PROBLEM FIXED!
(You can just edit enabled worlds! Please add it to wiki! :))
