### ISSUE TITLE
particle effects is not working

### ISSUE THREAD

**Issue by RussianAdmin** [iSach/UltraCosmetics#500]
Hello. I want to inform you that particle effects do not work in the plugin. A message appears in the chat that the particles are activated, but they do not appear. This applies to all particles in the plugin. Please fix it.

log is clear, core Spigot 1.12.2

**Comment by datatags** [comment]
Please make sure you don't have particles set to minimal in your client settings.

Closing since this is so old, please re-open if it's still an issue.
