### ISSUE TITLE
Loot boxes delete 1.16 Blocks

### ISSUE THREAD

**Issue by AmphyEX** [iSach/UltraCosmetics#501]
### What steps will reproduce the issue?  
1. Go to area with 1.16 Blocks
2. Open Loot box
3. 1.16 Blocks are deleted instead of placed back

### What was supposed to happen?
Blocks are supposed to be placed back.
### What happened? 
Blocks were deleted.
### What version of UltraCosmetics are you using?  
UltraCosmetics-2.5.8
### What Spigot version are you using? Paste the output of /version below.  
PaperMC v120
### What plugins do you have installed? Paste the output of /plugins below.  
![image](https://user-images.githubusercontent.com/34759737/88714203-0eefbc00-d0e2-11ea-925a-310979520bbf.png)
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
No errors as far as I was able to tell.

**Comment by floogal** [comment]
This wrecked my hub :(

**Comment by Danielh101** [comment]
> This wrecked my hub :(

I suggest having a development server to "test" new plugins or new features. Instead of just testing it on the live server where players play.

**Comment by datatags** [comment]
I think this is the same as #531, but the bug only causes clients to not see blocks that exist on the server, so if it's actually the same bug it shouldn't have actually destroyed your server?
