### ISSUE TITLE
Pet Wither turns into actual Wither on server restart

### ISSUE THREAD

**Issue by AmphyEX** [iSach/UltraCosmetics#502]
### What steps will reproduce the issue?  
1. When auto equip is on, equip the Wither pet
2. Stop, then start server
3. On rejoin, Wither Pet will be regular Wither and will attack players.

### What was supposed to happen?
Wither should stay in small form and not be aggressive.
### What happened? 
Wither turned into actual wither and attacked players.
### What version of UltraCosmetics are you using?  
2.5.8

### What Spigot version are you using? Paste the output of /version below.  
PaperMC v120
### What plugins do you have installed? Paste the output of /plugins below.  
![image](https://user-images.githubusercontent.com/34759737/88714574-9f2e0100-d0e2-11ea-8b37-a07d8e343a36.png)

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  

None that I could notice.

**Comment by datatags** [comment]
Fixed in 0d8a821
