### ISSUE TITLE
Server crashed randomly while using this plugin + a lot of internal errors with commands.

### ISSUE THREAD

**Issue by Welcome234** [iSach/UltraCosmetics#510]
Hello, I was excited to add this plugin to my server and then, unfortunately had to remove it due to server crashes and huge issues, so I removed it and everyone was not impressed and disappointed, please fix this issue.

My cosmetics are suppose to work as intended

Server has crash, crash report listed here
[crash-2020-08-24_20.44.27-server.txt](https://github.com/iSach/UltraCosmetics/files/5119742/crash-2020-08-24_20.44.27-server.txt)

I am using version 2.5.8

Spigot version
![image](https://user-images.githubusercontent.com/68016689/91084543-12745580-e644-11ea-94e3-4977ac96c5d4.png)

Plugins
![image](https://user-images.githubusercontent.com/68016689/91084510-04bed000-e644-11ea-8af7-3fd80b73ae04.png)

**Comment by datatags** [comment]
Doesn't look related to UltraCosmetics, unless maybe someone renamed a villager to "Bob" in the UC GUI? But it doesn't look related.
