### ISSUE TITLE
Server take a long time to load and error

### ISSUE THREAD

**Issue by PudimTotoso** [iSach/UltraCosmetics#514]
### What steps will reproduce the issue?  
1. Just start the server, when the plugin load it appears
2. 
3. 

### What was supposed to happen?
The plugin just start normally

### What happened? 
This error:
java.net.ConnectException: Connection timed out (Connection timed out)
at java.net.PlainSocketImpl.socketConnect(Native Method)

### What version of UltraCosmetics are you using? 
Lastest, 2.5.9-RELEASE

### What Spigot version are you using? Paste the output of /version below.  
Spigot 1.16.1 - This server is running CraftBukkit version git-Spigot-9639cf7-4b9bc9d (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

### What plugins do you have installed? Paste the output of /plugins below.  
Plugins (21): MPunishs, LuckPerms, SkinsRestorer, PiglinDupeFix, Timber, nAntiBot, PlaceholderAPI, WorldBorder, Vault, nReport, ProtocolLib, nLogin, WorldEdit, Legendchat, UltraCosmetics, Scoreboard-revision, Essentials, TAB, WorldGuard, EssentialsProtect, GriefPrevention

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
paste
error(s)
here
```

**Comment by datatags** [comment]
Not enough info to know for sure, but it sounds like MySQL settings are incorrect in config.yml.
