### ISSUE TITLE
multiple treasure chest bug + request

### ISSUE THREAD

**Issue by ghost** [iSach/UltraCosmetics#516]
### What steps will reproduce the issue?  
1.  have 2-3 people open treasure chests at the same time
2. make sure they near each other
3. 

### What was supposed to happen?
 all of them open treasure chests normallh
### What happened? 
their build egts mixed up and server lagged and crashed
### What version of UltraCosmetics are you using?  
latest
### What Spigot version are you using? Paste the output of /version below.  
This server is running BreadSpigot.-1.8.8
### What plugins do you have installed? Paste the output of /plugins below.  
 Plugins (35): MultiInv, FeatherEconomy, OpeNLogin, PlaceholderAPI, ClearLag, PlugMan, ZNPCS, Pl3xMOTD, Votifier, SilkSpawners, Multiverse-Core, MVdWPlaceholderAPI, FastAsyncWorldEdit, HubThat, VoidGenerator, AdvancedLobby, ViaVersion, Geyser-Spigot, Vault, ViaRewind, ShopGUIPlus, WorldEdit, IridiumSkyblock, AdvancedBan, RedProtect, ShopGUIPlusSilkSpawnersBridge, ProtocolLib, LibsDisguises, DiscordSRV, SuperbVote, PowerRanks, UltraCosmetics, Hawk, HolographicDisplays, CratesPlus
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
paste
error(s)    {no errors}
here
```
### Any additional information that you would like to provide that may be relevant to the issue?
maybe a way of making people unable to use open treasure chest from cosmetics gui and only able to use the npc + 1 player at a time treasure chest

**Comment by datatags** [comment]
Can't reproduce, was fixed at some point?
