### ISSUE TITLE
UltraCosmetics - Duplicate menu item with inventory shift click

### ISSUE THREAD

**Issue by MackenzieMolloy** [iSach/UltraCosmetics#517]
### What steps will reproduce the issue?  
1. Open inventory
2. Hold shift (or whatever your crouch button is), and click the cosmetics menu item

### What was supposed to happen?
Your inventory should be closed, and the item should not be duplicated
### What happened? 
Your inventory is closed, and the item is duplicated
### What version of UltraCosmetics are you using?  
2.5.9
### What Spigot version are you using? Paste the output of /version below.  
git-PaperSpigot-"4c7641d"
### What plugins do you have installed? Paste the output of /plugins below.  
LuckPerms, WorldEdit, VoidGenerator, PlaceholderAPI, NametagEdit, Vault, KiteBoard, WorldGuard, ProtocolLib, Citizens, UltraCosmetics, Essentials, EssentialsChat, HolographicDisplays, LiteBans, EssentialsSpawn, PremiumVanish, BungeeTabListPlus
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
None
```

**Comment by datatags** [comment]
Confirmed bug, only happens in creative.
