### ISSUE TITLE
Error spamming the console

### ISSUE THREAD

**Issue by Elric02** [iSach/UltraCosmetics#519]
An error keeps spamming my console (approximatively once per minute). No idea of why, couldn't relate to anything I'm doing in-game : it keeps popping even when I'm alone on the server and not using any cosmetics

### What version of UltraCosmetics are you using?
2.5.9

### What Spigot version are you using? Paste the output of /version below.
Paper version 186 (Minecraft 1.16.2)

### What plugins do you have installed? Paste the output of /plugins below.
AdvancedAchievements, Chunkmaster, Citizens,CoreProtect, CrazyEnchantments, EntityDetection, EntityTrackerFixer, Essentials,FastAsyncWorldEdit, Jobs, LibsDisguises, LimitPillagers, LuckPerms, Multiverse-Core, MythicMobs, NBTAPI, PlaceholderAPI, ProtocolLib, UltraCosmetics, Vault, WorldEdit, WorldGuard

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
https://pastebin.com/LBVD6qLx

**Comment by datatags** [comment]
Same as #534 which was fixed.
