### ISSUE TITLE
Tresures keep saying "Nothing"

### ISSUE THREAD

**Issue by zobos** [iSach/UltraCosmetics#52]
I enabled treasure on my server and whether you open it you always get "Nothing" I tried putting the rairety to 100% but still "Nothing"

**Comment by JHXSMatthew** [comment]
Hi,
Could please paste you config ( remove SQL info if you have) to http://pastebin.com/ .
Cheers.

**Comment by zobos** [comment]
Here you go:
http://pastebin.com/V8Wtr8VP

**Comment by iSach** [comment]
It means you have everything and Money Loot is disabled.
