### ISSUE TITLE
Duplicating items 

### ISSUE THREAD

**Issue by unholymac** [iSach/UltraCosmetics#528]
### What steps will reproduce the issue?  
1. select any gadget
2. open a chest
3. press 5 on any item in the chest and it will swap it with the gadget
4. close the chest and then clear cosmetic and the item will still be in the chest

### What was supposed to happen?
should not be able to be put into a chest and used to duplicate
### What happened? 
people can give themself any item thats in the gui
### What version of UltraCosmetics are you using?  
2.5.9 since 2.5.10 doesn't work on 1.16.3
### What Spigot version are you using? Paste the output of /version below.  
Tuinity 1.16.3
### What plugins do you have installed? Paste the output of /plugins below.  
[
<img width="647" alt="Capture" src="https://user-images.githubusercontent.com/59938744/103106665-42058f80-462f-11eb-9ad7-79d8bb4032b2.PNG">
](url)
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
no errors
```

**Comment by unholymac** [comment]
This is a massive issue and i cannot use this on my survival server! Is this bug being fixed?

**Comment by Baterka** [comment]
I was unable to put gadget into chest by clicking 5 or any other way.

**Comment by Baterka** [comment]
I confirm this is a real bug
