### ISSUE TITLE
Mounts Ghostblocks 1.16.4 R0.1 

### ISSUE THREAD

**Issue by supermem99** [iSach/UltraCosmetics#531]
### What steps will reproduce the issue?  
1. Open uc menu
2. choose mounts
3. choose mountsoffire

### What was supposed to happen?
1. I want normally to ride the mount and the floor should replaced with the blocks.
### What happened? 
1. The Floor was replaced with the "firecolors" but after disappearing, the replaced blocks were invisible like barriers.
### What version of UltraCosmetics are you using?  
latest 2.5.10 Ultra Cosmetics
### What Spigot version are you using? Paste the output of /version below.  
1. 1.16.4 Paper latest R0.1
### What plugins do you have installed? Paste the output of /plugins below.  
Its not caused by other plugins. I tested it with clean install. So i havent any other plugins except ultra cosmetics
# Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
nope
```
### Any additional information that you would like to provide that may be relevant to the issue?
Its maybe a clientside bug. (ghosteblocks) But it seems like to be on only new blocks. Example prismarinestairs

**Comment by datatags** [comment]
Good eye noticing it only happens with new blocks, this is fixed in dev builds which are in the Discord.
