### ISSUE TITLE
Crash on mount molton snake

### ISSUE THREAD

**Issue by supermem99** [iSach/UltraCosmetics#532]
### What steps will reproduce the issue?  
1.  Open Uc menu
2. choose mounts
3. choose Moltonsnake

### What was supposed to happen?
flying with the molton snake through air
### What happened? 
server crashes 
[link](https://pastebin.com/xA3Dcyj4)
### What version of UltraCosmetics are you using?  
2.5.10
### What Spigot version are you using? Paste the output of /version below.  
1.16.4 R0.1 paper
### What plugins do you have installed? Paste the output of /plugins below.  
citizens latest
vault
protocolllib latest
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
[Link](https://pastebin.com/XVb7SWhH)
```

**Comment by datatags** [comment]
Please try with latest dev build (available in Discord) and see if it's still an issue. If so, please also include your full log as this error doesn't seem to describe the issue directly.
