### ISSUE TITLE
Suggestion - Add arrow and death effects

### ISSUE THREAD

**Issue by VoltroXP** [iSach/UltraCosmetics#536]
As the title states, add arrow effects and death effects. They are one of the few cosmetics that can be really used during PVP, and they are quite easy to make.

Some examples for arrow effects could include water, lava, confetti, love, sparkly, green/grass, magic, and music.
Some examples for death effects could include lightning, flames/lava, magic, anger/rage, confetti, and blood.

**Comment by datatags** [comment]
I think this is out-of-scope for UltraCosmetics at the moment. As in https://github.com/iSach/UltraCosmetics/issues/557#issuecomment-998345778, UC is more about active player-controlled gadgets. I'll keep it in mind though 🙂
