### ISSUE TITLE
Mysql database system does not work

### ISSUE THREAD

**Issue by Nubebuster** [iSach/UltraCosmetics#539]
I am using version 2.5.10 on spigot1.16.5

Using the mysql file system does not work. New players are put into the database, but keys and gadget ammo are not stored in the mysql database. Also the buying of keys and ammo does not work at all. Money is deducted, but the item is not added to the player. I have tried using clean configs and restarting the server.

Here is a video showing the problem: 
https://youtu.be/ds1I9GS3omw

Note: The error seen in the console is from libsdisguises, not this plugin.

**Comment by ARR4NN** [comment]
When using MySQL you need to configure it with a host name and all that info the local host wont work, please configure correctly and try again.

**Comment by MeowRay** [comment]
Using mysql8 will cause the bug

> When using MySQL you need to configure it with a host name and all that info the local host wont work, please configure correctly and try again.

Using mysql8 will cause the bug, it should be fixed

**Comment by datatags** [comment]
This also happens when you restart the server between config changes, right? And just to confirm, there are no console errors?

**Comment by datatags** [comment]
Closing due to lack of information. The MySQL module has just been reworked so the issue may be fixed anyway.
