### ISSUE TITLE
Can't execute the open menu command in chestcommand?

### ISSUE THREAD

**Issue by coolshing** [iSach/UltraCosmetics#541]
Hello, I have a question to ask, do you have any instructions to help others open the menu? I hope that players can open /uc menu effects separately through [chestcommand](https://dev.bukkit.org/projects/chest-commands/files) without having to enter commands, or there are other ways to achieve this effect.

By the way, when I  execute the /uc menu effects t in chestcommand that is a plugin , there will be a crash

**Comment by ARR4NN** [comment]
If an action opens another menu of Chest Commands or a GUI of an external plugin, set **KEEP-OPEN: true**.
Thanks
