### ISSUE TITLE
Rudolfs Antlers positioned weirdly and lag behind when riding

### ISSUE THREAD

**Issue by Chris6ix** [iSach/UltraCosmetics#543]
### What steps will reproduce the issue?  
1. Summon the Rudolf Mount and ride it

### What was supposed to happen?
Antlers should be on Rudolfs head
### What happened? 
Antlers are in a lot of weird positions and lag behind when riding instead of being stuck on the head
### What version of UltraCosmetics are you using?  
UltraCosmetics-2.5.11-RELEASE
### What Spigot version are you using? Paste the output of /version below.  
Paper version git-Paper-142 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8bebf48)
### What plugins do you have installed? Paste the output of /plugins below.  
Plugins (41): BetterConcrete, Bookshelf, CommandCooldown*, CustomEnderChest, DeluxeMenus, dynmap, Essentials, EssentialsChat, FlyPerms, GoldenEnchants, GSit, Hat, HolographicDisplays, HoloMobHealth, HomeGUI, InteractionVisualizer, JoinRules, LightAPI, LinksPlus, LuckPerms, Multiverse-Core, Multiverse-Inventories, NexEngine, PL-Hide, PlaceholderAPI, PlayerPortal, PlayerWarps, Playtimes*, PlugMan, ProtocolLib, QuickShop, RealScoreboard, SilkSpawners, TAB, UltimateCatcher, UltimateTimber, UltraCosmetics, Vault, WorldEdit, WorldGuard, XpBottles
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
No errors
### Any additional information that you would like to provide that may be relevant to the issue?
Screenshots of what I mean:
![2021-08-01_17 57 00](https://user-images.githubusercontent.com/65610536/127778383-32b06b6e-881d-44c0-8e81-db1ce2b2108a.png)
![2021-08-01_17 57 22](https://user-images.githubusercontent.com/65610536/127778388-4e7ec528-417d-4911-b4c7-1bec873b650b.png)
![2021-08-01_18 25 29](https://user-images.githubusercontent.com/65610536/127778389-a510d4ac-b544-411f-a610-3fcf9b827df6.png)
![2021-08-01_18 26 55](https://user-images.githubusercontent.com/65610536/127778391-d4ed890e-0954-486e-9e66-f2f6b09d9aba.png)
![2021-08-01_17 56 15](https://user-images.githubusercontent.com/65610536/127778374-c4223705-d90b-466a-914c-e0b344e8e35e.png)
![2021-08-01_17 56 28](https://user-images.githubusercontent.com/65610536/127778376-dd45eddb-4235-4261-8ec4-376f281f8c1f.png)
![2021-08-01_17 56 32](https://user-images.githubusercontent.com/65610536/127778378-2852ae7a-7e7e-4eb8-b5a4-ea373391c932.png)

**Comment by datatags** [comment]
This is unfortunately unfixable without using a resource pack or mod, since the client doesn't know there's a relationship between the horse and the armor stands, so the armor stands are moved server-side, which has lag from the client's perspective.
