### ISSUE TITLE
Suggestion: Clear Cosmetics on World Change

### ISSUE THREAD

**Issue by doublehelix457** [iSach/UltraCosmetics#545]
I quite like that cosmetics can be enabled in a world. However, it'd be nice to have the option to clear any active cosmetics when a player changes into a world without cosmetics.

For example, 
a player might morph into a blaze in the hub world,
change to a bedwars world when the game starts, 
and fly over to the other side of the map.

**Comment by datatags** [comment]
This is already a feature, but it had a bug where it didn't clear cosmetics when a player had only a morph equipped. This is fixed in dev builds which you can find in the Discord.
