### ISSUE TITLE
UltraCosmetics is disabled in this world

### ISSUE THREAD

**Issue by NinjagoKristian** [iSach/UltraCosmetics#547]
I saw the previous post about this (My server says: "Ultracosmetics are disabled in this world" how do I re-enable?). I do not have the Enabled-Worlds config area in the config.yml file. How do you enable it? If you are wondering I downloaded the .jar directly from this github.

**Comment by datatags** [comment]
I'm figuring this has been resolved in one way or another by now, but for anyone else you can add this section to your config manually:
```yaml
Enabled-Worlds:
- hub
- survival
```
Etc
