### ISSUE TITLE
Particles

### ISSUE THREAD

**Issue by bubbakadriu** [iSach/UltraCosmetics#550]
### What steps will reproduce the issue?  
1.  Install GeyserMC
2.  Join using a mobile device
3.  Equip a walk trial

### What was supposed to happen?
Walk trial equip with no lag

### What happened? 
Alot of lag on mobile devices when using particles

### What version of UltraCosmetics are you using?  
latest

### What Spigot version are you using? Paste the output of /version below.  
latest

### Any additional information that you would like to provide that may be relevant to the issue?
Please add a way for us to edit the amount of particles per tick. When using the wings, any mobile user lags. If there is a way to change how many ticks per second i can fix the lag. Heres an example:

FreezeCannon:
    # Description of this cosmetic.
    Description:
    - '&7&oTransform the floor into a rink!'
    Cooldown: 8.0
    # Should it affect players? (Velocity, etc.)
    Affect-Players: true
    # if true, the gadget will be enabled.
    Enabled: true
    # if true, the description of gadget will be showed.
    Show-Description: true
    # if true, it'll be possible to find
    # it in treasure chests
    Can-Be-Found-In-Treasure-Chests: true
    Particle-Tick-Rate: 1

**Comment by datatags** [comment]
Thanks for making an issue for this! By changing the amount of "particles per tick" do you mean like a multiplier? Like "Particle-Tick-Rate: 0.5" means 50% of the usual particles?

Also, it's good to specify exactly what version of Spigot/UC you're using rather than just saying "latest" even if it is the latest. Thanks!

**Comment by bubbakadriu** [comment]
Thanks for your response, sorry i dont know much about java plugins or how particles work but yeah basically i want less particles to spawn for the walk trails/wings. If possible to add an option to change how many particles spawn per second so i can decrease them and the lag. Sorry for not stating the server version, i actually dont know it and my panel says its autos to latest. Thanks :)

**Comment by datatags** [comment]
Ok sounds good, I might take a look at doing that if I have some time. :)

**Comment by datatags** [comment]
Here's a "development build" to try out. Most particle cosmetics now have a "Particle-Multiplier" option in the config. The ones that don't are the ones that only create 1-2 particles per tick anyway. You can set Particle-Multiplier to 0 for the minimum amount of particles. If the minimum is still too many on some of them, let me know.

Thanks!

(the file is a .zip, change the extension to .jar after downloading)
[UltraCosmetics-2.5.11-RELEASE.zip](https://github.com/iSach/UltraCosmetics/files/7478412/UltraCosmetics-2.5.11-RELEASE.zip)

**Comment by bubbakadriu** [comment]
Wow you're awesome thanks dude
