### ISSUE TITLE
Filter by owned cosmetics

### ISSUE THREAD

**Issue by GreenArrowlol** [iSach/UltraCosmetics#555]
Hey so this is a suggestion I randomly thought of, so whenever we open a category like, hats, pets then maybe a item named `filter owned` would be cool here it filters all the cosmetics we owned and priorities them above cosmetics that we do not and it would be cool to see the item with a hopper as it gives us the vibe of sorting 

If did not understand the suggestion above you may ping me in the discord server as its easy to talk there ArrowTan#1360

**Comment by datatags** [comment]
I just noticed there is a config option to not show cosmetics the player doesn't have permission for (`No-Permission.Dont-Show-Item`), but obviously that sets it for everyone so this would still be a good thing to implement.
