### ISSUE TITLE
Bedwars1058

### ISSUE THREAD

**Issue by bosszepro** [iSach/UltraCosmetics#557]
Hii

It is possible to do the cosmetics with Bedwars1058 like the shop keeper, victory dances etc ?

**Comment by datatags** [comment]
Could you explain in a little more detail as I'm not familiar with Bedwars1058. Are you wanting the in-game shop keeper to sell cosmetics? And what do you mean by victory dances?

**Comment by bosszepro** [comment]
It’s a Bedwars plugin like hypixel.

Shop keeper is the man’s and he sell wood swords obi etc…

Victory dance is when you win a game you have a dance like an Enders’ dragon or a wither etc different textures of wood and all the cosmetics like hypixel.

**Comment by datatags** [comment]
> It’s a Bedwars plugin like hypixel.
> 
> Shop keeper is the man’s and he sell wood swords obi etc…
> 
> Victory dance is when you win a game you have a dance like an Enders’ dragon or a wither etc different textures of wood and all the cosmetics like hypixel.

Okay, but precisely what features are you wanting to be added to UltraCosmetics?

**Comment by bosszepro** [comment]
Victory dance, kill effect, bow trail, death cries, shopkeeper skin, kill message and bed break effects

**Comment by datatags** [comment]
I think this is a little out-of-scope for UltraCosmetics, since UC is all about player-controlled gadgets and such.
