### ISSUE TITLE
[Suggestion] Set Gadget Cooldown to 0 for op Players / for specific Permission

### ISSUE THREAD

**Issue by Chris6ix** [iSach/UltraCosmetics#559]
Hey! It would be really nice if you could add an option that removed all Cooldowns for op Players / add a permission that when given removes all Cooldowns from Gadgets.

**Comment by datatags** [comment]
Fixed in a5616e64d9bcf24f78f1bbee19ebae9cfc1b930e. Permission is ultracosmetics.bypass.cooldown, does not default to OP because it's pretty experimental at this point. Dev build will be out shortly.

**Comment by Chris6ix** [comment]
Thank you for implementing my suggestion so fast ;)
