### ISSUE TITLE
Please help Sach!

### ISSUE THREAD

**Issue by iScarf** [iSach/UltraCosmetics#56]
So basically, i have your plugin installed (AMAZING) and i was wondering if there was any possible way to have some groups not have permisssion to use certain particle effects. like, Guests cannot use Flame rings, you must find them in chest. any help please?

**Comment by Noodles0809** [comment]
yes on the wiki are perms for all partiles

**Comment by iSach** [comment]
http://bit.ly/PermsUC

Here are the permissions.
