### ISSUE TITLE
Gadget "Thor's Hammer" can be picked up by Zombies and be turned into a normal Iron Axe with custom Name

### ISSUE THREAD

**Issue by Chris6ix** [iSach/UltraCosmetics#560]
### What steps will reproduce the issue?  
1. Get the Gadget "Thor's Hammer"
2. Throw it at a Zombie that can pick up items (If you can't find one (not all Zombies can pick up loot), use `/minecraft:summon minecraft:zombie ~ ~ ~ {CanPickUpLoot:true}`
3. Kill the Zombie and you get a normal Iron Axe with the Name "Thor's Hammer"

### What was supposed to happen?
"Thor's Hammer" should not be able to be picked up by Mobs
### What happened? 
The Gadget was picked up by the Zombie and turned into a normal Iron Axe (With a custom name) 
This could be used by players to infinitely create Free Iron Axes
### What version of UltraCosmetics are you using?  
2.5.11
### What Spigot version are you using? Paste the output of /version below.  
This server is running Paper version git-Paper-406 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b1af5ea on ver/1.17.1)
### What plugins do you have installed? Paste the output of /plugins below.  
Plugins (41): BetterConcrete, Bookshelf, CommandCooldown, CustomEnderChest, DeluxeMenus, Duels, dynmap, Essentials, EssentialsChat, FlyPerms, GSit, Hat, HolographicDisplays, HoloMobHealth, HomeGUI, InteractionVisualizer, JoinRules, LightAPI, LinksPlus, LuckPerms, Multiverse-Core, Multiverse-Inventories, NexEngine, PL-Hide, PlaceholderAPI, PlayerPortal, PlayerWarps, Playtimes*, PlugMan, ProtocolLib, QuickShop, RealScoreboard, SilkSpawners, TAB, UltimateCatcher, UltimateTimber, UltraCosmetics, Vault, WorldEdit, WorldGuard, XpBottles
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
No Errors
### Any additional information that you would like to provide that may be relevant to the issue?
No

**Comment by datatags** [comment]
Fixed in dev builds, thanks for reporting it!

**Comment by Chris6ix** [comment]
No problem! Thanks for fixing it so quickly :)
