### ISSUE TITLE
Particle Effects

### ISSUE THREAD

**Issue by rishabhk571** [iSach/UltraCosmetics#563]
[### What steps will reproduce the issue?  
1. Tried Restarting
2. Tried Reinstalling
3. Tried Every Permission

### What was supposed to happen?
Particles would have been seen when selecting any of them on the player

### What happened? 
Particles are neither being displayed on Java nor in pocket edition, any effect is not working

### What version of UltraCosmetics are you using?  
v.2.6 Dev Build

### What Spigot version are you using? Paste the output of /version below.  
This server is running Purpur version git-Purpur-1489 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: ed169a3 on HEAD)

### What plugins do you have installed? Paste the output of /plugins below.  
Plugins (37): AuctionHouse, AureliumSkills, BeautyQuests, BetterTeams, Bounty*, Citizens, DeluxeHub, DiscordSRV, Duels, EconomyShopGUI, Essentials, floodgate, Geyser-Spigot, GriefPrevention, GSit, ImageMaps, LevelledMobs, LPC, LuckPerms, Maintenance, nLogin, PlaceholderAPI, ProtocolLib, SilkSpawners, SimplePolice, SkinsRestorer, Slimefun, StaffPlus, TAB, UltimateAntiBot, UltimateHomes, UltimateTimber, UltraCosmetics, Vault, ViaBackwards, ViaVersion, WorldEdit

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
paste
error(s)
here
```
### Any additional information that you would like to provide that may be relevant to the issue?
I also attached 2 images where i selected Green Sparks particle effect but didnt got it 
![Bug report 1 image](https://user-images.githubusercontent.com/89680511/148787986-25b0ca8d-e408-4cb0-bb7f-40850cb2fd38.png)

![Bug report 2 image](https://user-images.githubusercontent.com/89680511/148788033-429ef9e6-8966-41bc-9013-1578b46c547f.png)

**Comment by datatags** [comment]
Can't reproduce, did you make sure you don't have particles set to minimal in your client settings?

**Comment by rishabhk571** [comment]
Can u please share a screenshot where can i find that settings? :)

**Comment by datatags** [comment]
1. [Click options](https://i.imgur.com/BQWHXlJ.png)
2. [Click Video Settings](https://i.imgur.com/LUz85IE.png)
3. [Click Particles](https://i.imgur.com/eWzRgQn.png)

**Comment by rishabhk571** [comment]
Done, Thanks
