### ISSUE TITLE
Fix GitHub Actions

### ISSUE THREAD

**Issue by datatags** [iSach/UltraCosmetics#565]
Not using the issue template as it's not related to the UltraCosmetics plugin itself, but the GitHub repo.

It'd be nice to figure out how to make GitHub Actions work again. Currently it doesn't work because UC requires NMS from several different versions of MC, which can't be redistributed.

One idea I had is to make a Gradle task that builds each required version of Spigot automatically. With this solution, not only would the bot be able to compile it, but it would also make it easier for new contributors to get set up.

Any other ideas are appreciated.

**Comment by DartPower** [comment]
Check this please :) #566
But this is very simple, temporary good fix i think.

**Comment by datatags** [comment]
Fixed in d0e7021 :)
