### ISSUE TITLE
Issues with 1.16.5 Error While Enabling

### ISSUE THREAD

**Issue by TheGamersBrew** [iSach/UltraCosmetics#568]
### What steps will reproduce the issue?

1. Running a Mohistmc set up for Plugin Support for a Cursed Forge server
2. Added your Plugin version 2.5.11
3. Error occurred (see Pic)

![image](https://user-images.githubusercontent.com/77638191/149609104-1e743c80-00ec-4b96-bcf4-5e41e5350f3f.png)

### What was supposed to happen?

Run properly as 1.16.5 is getting updates for mod packs and will be the go to going forward for updating older mods and mod packs.

### What happened instead?

Error when loading server

### What version of UltraCosmetics are you using? Do not say 'latest'.

V2.5.11

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

Spigot

### What plugins do you have installed?

![image](https://user-images.githubusercontent.com/77638191/149609166-1ef3887b-9296-4ddb-8d20-ecf28d472e2a.png)

### Are there any errors in the console or in logs?

14.01 23:29:47 [Server] Server thread/INFO Enabling UltraCosmetics v2.5.11
14.01 23:29:47 [Server] Startup01/15/2022 - UltraCosmetics [INFO]: -------------------------------------------------------------------
14.01 23:29:47 [Server] Startup01/15/2022 - UltraCosmetics [INFO]: UltraCosmetics v2.5.11 is loading... (server: 1.16.4)
14.01 23:29:47 [Server] Startup01/15/2022 - UltraCosmetics [INFO]: Thanks for downloading it!
14.01 23:29:47 [Server] Startup01/15/2022 - UltraCosmetics [INFO]: Plugin by iSach.
14.01 23:29:47 [Server] Startup01/15/2022 - UltraCosmetics [INFO]: Link: http://bit.ly/UltraCosmetics
14.01 23:29:47 [Server] Startup01/15/2022 - UltraCosmetics [INFO]: Initializing module v1_16_R3
14.01 23:29:47 [Server] Startup01/15/2022 - UltraCosmetics [INFO]: bStats enabled!
14.01 23:29:47 [Server] Server thread/ERROR Error occurred while enabling UltraCosmetics v2.5.11 (Is it up to date?)

**Comment by datatags** [comment]
There should be more to the error below what you posted, could you send that part too?

**Comment by datatags** [comment]
Closing due to 10 days without a response. Please re-open if you can provide additional information.
