### ISSUE TITLE
Use a more widely-known license

### ISSUE THREAD

**Issue by A248** [iSach/UltraCosmetics#569]
UltraCosmetics uses its own unique license. While this has good intentions, it unnecessarily complicates contributing and prevents legitimate re-use of ideas and code in other projects. I don't think I need to explain why this might be an issue for other programmers wishing to incorporate code from UltraCosmetics in a legitimate and honest fashion.

https://github.com/iSach/UltraCosmetics/blob/12b6b67aea6b29bbff43fd0a1f858c5fde5b9c89/LICENSE#L1

I suggest the GNU General Public License, as it would seem to fit your inclinations. The GPL will keep UltraCosmetics free software (as in *freedom*) as it ought to be and as you seem to want it. I very much agree, too -- I release my own code under the GPL family of licenses, in almost every case. You could even opt for the GNU Affero General Public License, as I have done for my own plugin, LibertyBans.

**Comment by datatags** [comment]
Thanks for this, I've been meaning to mention it to the author. @iSach, any thoughts?

**Comment by datatags** [comment]
Closed in [08f0875](https://github.com/iSach/UltraCosmetics/commit/08f0875b7688994ccfc50285ca4c3097ed821c90) :D
