### ISSUE TITLE
Please read fast! | Particles not working?

### ISSUE THREAD

**Issue by iExplosive** [iSach/UltraCosmetics#57]
Hello! The particles seem to not work for me.... Does the plugin need ParticleLib?

**Comment by Noodles0809** [comment]
Yes

**Comment by JHXSMatthew** [comment]
No, not exactly. 
Did you put the world in "enable world list" in config file ?

**Comment by iExplosive** [comment]
Thank you much better :dancer:

**Comment by iSach** [comment]
@Noodles0809 Please don't tell things that aren't true.
