### ISSUE TITLE
Everything spawns and then despawns right after?

### ISSUE THREAD

**Issue by tuckerandlexus** [iSach/UltraCosmetics#58]
Hi there, I was wondering why items will spawn and despawn right after or if I'm morphed it unmorphs me right after. It's the same for all of them. I am using spigot 1.8.8 and ultra cosmetics 2.0.6. The plugin isn't in red and it created all the config and other folders. No errors are appearing in the log? I have enabled everything in the config file? 

Thank you.

**Comment by JHXSMatthew** [comment]
Hi,
Please make sure you put the world name to "enable world list" in configure file.

**Comment by tuckerandlexus** [comment]
Omg that is so amazing! I love this plugin. Thank you so much :D

**Comment by JHXSMatthew** [comment]
Enjoy iSach's amazing plugin. Please close the issue if It solves  :).
