### ISSUE TITLE
Treasure keys not given when using MySQL

### ISSUE THREAD

**Issue by JAHMCR** [iSach/UltraCosmetics#587]
### What steps will reproduce the issue?

1. Enable MySQL in the config.yml
2. Run the server
3. Try to purchase a treasure key
4. Check the available keys, it always display 0

This also happens when trying to give keys with the command /uc give key 1, no key is actually given

### What was supposed to happen?

When purchasing a key it should be given to the user

### What happened instead?

No key is being given to the player

### What version of UltraCosmetics are you using? Do not say 'latest'.

UltraCosmetics-2.6-RELEASE

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

Paper build 216

### What plugins do you have installed?

Plugins (19): CMILib, CoreProtect, Essentials, EssentialsGeoIP, EssentialsSpawn, GriefPrevention, Jobs, mcMMO, Multiverse-Core, PlaceholderAPI, ResourceWorld, Shops, SkinsRestorer, UltraCosmetics, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit

### Are there any errors in the console or in logs?

No errors

**Comment by datatags** [comment]
Much of the MySQL code has been recently rewritten, could you see if the issue still happens with a dev build? (Found in #beta-testing in the Discord or in [Actions](https://github.com/iSach/UltraCosmetics/actions))

**Comment by JAHMCR** [comment]
Thanks @datatags, it does work on that latest DEV version

**Comment by datatags** [comment]
Cool 👍🏻
