### ISSUE TITLE
Switching from Flatfile to Mysql

### ISSUE THREAD

**Issue by MCTyler** [iSach/UltraCosmetics#59]
I successfully created the MySql database and connected to it but Is there a import or migrate command to get the old data into this file? Players have a lot of Ammo. Thanks!

**Comment by iSach** [comment]
Not yet, sorry, I'll add a converter in next update.

**Comment by MCTyler** [comment]
Sry for the dbl post, here and Spigot, but after I made the one on Spigot I reviewed your plicies and it said to use Github....Thanks!

**Comment by MCTyler** [comment]
That will be a sweet surprise for some players!

**Comment by iSach** [comment]
Still planned, sorry for long delay.

**Comment by DeltaEvolution** [comment]
If you want I can work on iSach ?

**Comment by iSach** [comment]
@DeltaEvolution If you want yes make a pull request I will implement it thanks :p
