### ISSUE TITLE
Third person view is not working when switching Morph

### ISSUE THREAD

**Issue by JAHMCR** [iSach/UltraCosmetics#591]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

1. Enable Morphs in config.yml
2. Select a Morph
3. Enable 3rd person view in the menu
4. Switch to a different Morph

### What was supposed to happen?

The Morph is updated immediately for the player without needing to disable and enable 3rd person view again

### What happened instead?

The Morph is updated only when the player disable and enable 3rd person view again

### What version of UltraCosmetics are you using? Do not say 'latest'.

UltraCosmetics 2.6.1 DEV b11

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

Paper build 216

### What plugins do you have installed?

Plugins (19): CMILib, CoreProtect, Essentials, EssentialsGeoIP, EssentialsSpawn, GriefPrevention, Jobs, mcMMO, Multiverse-Core, PlaceholderAPI, ResourceWorld, Shops, SkinsRestorer, UltraCosmetics, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit

### Are there any errors in the console or in logs?

No errors

**Comment by datatags** [comment]
I couldn't reproduce the issue, the morph updated right away for me. Maybe check if LD is up-to-date? (also your plugin list doesn't actually contain LD?)

**Comment by JAHMCR** [comment]
Will try again with the latest DEV build you uploaded and then let you know

**Comment by JAHMCR** [comment]
Just confirmed that it's working fine but just when selecting friendly mobs, not when selecting hostile ones. For example, if I select a Pig and then select a Chicken it works, but if I have a Pig selected and then select a Blaze or Enderman it does not update until toggling the 3rd person view. Once the hostile one is visible, I cannot switch to another hostile, just a friendly one without toggling again the 3rd person view.

**Comment by datatags** [comment]
Not sure what to tell you, I tried the example you gave as well as several other combinations and they all worked fine without having to toggle third person view. Maybe try an LD dev build? https://ci.md-5.net/job/LibsDisguises/

It looks like Paper build 216 is the last build that supports 1.18.1, and UC 2.6.1-b11 is built only for 1.18.2, not 1.18.1. I'm not sure that has anything to do with it though.

**Comment by JAHMCR** [comment]
Just updated to the latest Paper build 267 and downloaded the latest LibDisguises DEV build, still facing the same issue.

Here is my updated plugin list: BungeeGuard, LibsDisguises, LuckPerms, ProtocolLib, SkinsRestorer, UltraCosmetics, Vault, ViaBackwards, ViaRewind, ViaVersion

**Comment by JAHMCR** [comment]
I just noticed something strange behavior when selecting the Elder Guardian, it appear and disappear immediately, so I guess it's something in my server, will check carefully and let you know ASAP

**Comment by datatags** [comment]
No idea why I can't reproduce this on my standard test server, but on a fresh one the issue does happen. Turns out this is a LibsDisguises bug, see: https://github.com/libraryaddict/LibsDisguises/issues/650

**Comment by JAHMCR** [comment]
Thanks @datatags, hopefully they address this issue soon.

Just out of curiosity, what versions of ProtocolLibs and LibDisguises do you have on your test server? Did you change any of their default configurations?

**Comment by datatags** [comment]
> Thanks @datatags, hopefully they address this issue soon.
> 
> Just out of curiosity, what versions of ProtocolLibs and LibDisguises do you have on your test server? Did you change any of their default configurations?

Looks like ProtocolLib-4.8.0 and LibsDisguises build 1089. No config changes that I'm aware of

**Comment by datatags** [comment]
Turns out this is caused by the `TallSelfDisguises` option found in LibsDisguises's `players.yml`, and not an actual bug.
