### ISSUE TITLE
Add more (specific) WorldGuard flags

### ISSUE THREAD

**Issue by Chris6ix** [iSach/UltraCosmetics#597]
### Describe the feature

Currently, UC has 2 WG flags: Cosmetic and Treasure
But if you have a WG region where you want to for example disable the use of mounts, but allow the use of the other cosmetics, you cannot do that because setting the "Cosmetic" flag either completely allows the use of ALL Cosmetics or disallows ALL Cosmetics...

So it would be great if there were multiple WG flags, one for each "category" of cosmetics (pets, mounts, particles etc...).
This would allow a lot more fine control over what cosmetics can be used where :)

### When/how would it be used?

/\

### Are there alternatives?

I don't think so

### Additional information

/

**Comment by datatags** [comment]
I think this could be done with a single flag and use of WorldGuard's EnumFlag class: https://github.com/EngineHub/WorldGuard/blob/master/worldguard-core/src/main/java/com/sk89q/worldguard/protection/flags/EnumFlag.java

These new flag(s) would replace the existing `uc-cosmetics` flag, correct?

**Comment by Chris6ix** [comment]
Yes, I guess this would replace the `uc-cosmetics` flag as It's then not needed anymore (If you want to allow/disallow every cosmetic, then you would set all of these flags to either `allow` or `deny`)

**Comment by datatags** [comment]
Well I looked at the SetFlag class and it seems not all that great for this use case, so I'm thinking I'll just make a flag for each category, as you said. I'll keep `uc-cosmetics` so it's easy to make a whitelist or blacklist thing with the flags, since I'll have it only check `uc-cosmetics` if there's no set value for `uc-<category>`

**Comment by datatags** [comment]
I spent a bunch of time yesterday trying to get WG to recognize the different flags and flag handlers for each category but it wants each flag to have its own class, which is super weird. So I think I'll try keeping the `uc-cosmetics` flag (for usability) and also have a flag like `uc-blocked-categories` where you can specify categories that shouldn't be allowed. For `uc-blocked-categories` to apply, `uc-cosmetics` will have to be set to allow.

**Comment by Chris6ix** [comment]
Sure, this will achieve the same result, just with a different method!
Thank you for spending all that Time on this :)

**Comment by datatags** [comment]
Done in 46d6467dd7e4585d7cd1e53f8de7c23d86112262
