### ISSUE TITLE
TnT/Pearl/Paintball Breaking Item Frames and Paintings

### ISSUE THREAD

**Issue by rocky143** [iSach/UltraCosmetics#6]
Using latest version of the plugin and when TnT gadget is used, item frames and paintings are being destroyed.
This happens no matter if the area is protected or not.
WorldGuard or any other protection plugin is being bypassed by it.

**Comment by rocky143** [comment]
Alright, just tested and seems like Ethereal Pearl also destroying paintings/item frames time to time.

**Comment by rocky143** [comment]
Sorry but another issue. Paintball gun is able to destroy paintings.

**Comment by iSach** [comment]
Hello,

The issues have been fixed and the bug fixes will be included in the next update.

Thanks for your report.

Best Regards,
Sacha.
