### ISSUE TITLE
clicking 'cancel' in buykey menu closes menu

### ISSUE THREAD

**Issue by dennishzg** [iSach/UltraCosmetics#602]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

1. execute `/uc menu` click on 'Treasure Keys' OR execute `/uc menu buykey`
2. click on 'CANCEL'

### What was supposed to happen?

go back to the main menu, same behaviour as clicking on 'PURCHASE' (successful purchase).
open ultracosmetics main menu **OR (if enabled) execute the command specified at `Back-To-Main-Menu-Custom-Command` in config.yml** (related issue: https://github.com/iSach/UltraCosmetics/issues/601)

### What happened instead?

the buykey menu is closed

### What version of UltraCosmetics are you using? Do not say 'latest'.

UltraCosmetics-2.7-RELEASE

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

This server is running Paper version git-Paper-357 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: f210f67)

### What plugins do you have installed?

Plugins (35): AdvancedRegionMarket, Autorank, Chatty, Chunky, ChunkyBorder, CMILib, CoreProtect, DeadChest, DeluxeMenus, DropHeads, dynmap, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsDiscord, EssentialsProtect, EssentialsSpawn, FarmControl, Images, Jobs, LibsDisguises, LuckPerms, Maintenance, MiniMOTD, Multiverse-Core, OpenInv, PlaceholderAPI, ProtocolLib, ResourceWorld, SuperVanish, TabList, UltraCosmetics, Vault, WorldEdit, WorldGuard

### Are there any errors in the console or in logs?

no

**Comment by datatags** [comment]
Changing this to a feature request because this was previously intended behavior, but it seems like a reasonable change.
