### ISSUE TITLE
Translations, switching locale feature

### ISSUE THREAD

**Issue by dennishzg** [iSach/UltraCosmetics#606]
### Describe the feature and how it would be used

A feature that allows the user to quickly change the language of the plugin via a setting in the config.yml.
This feature would also improve the collaboration process a lot (see below).
Many plugins already have this feature and it would be awesome if UltraCosmetics would have it too.
I saw issue https://github.com/iSach/UltraCosmetics/issues/328 but maybe you can reconsider this feature because i don't understand why that issue was closed.

---

The setting in the config.yml would look like this:
```yaml
locale: de
```

The translation files are stored like this:
```
locale/
├─ messages_en.yml
├─ messages_de.yml
```

The messages_en.yml is always used as a fallback language in case a translation is missing.

**I would love to add the german translation once this feature has been added! 😄** 

### Are there alternatives?

the current solution via the [wiki translations page](https://github.com/iSach/UltraCosmetics/wiki/Translations) is inconvenient. 

- copy and pasting from a pastebin is inconvenient and not user-friendly. you have to manually update the messages.yml everytime a change is made.
- no version control system for the translation files
- collaboration is limited

**Comment by datatags** [comment]
Not sure if you've been keeping up with the stuff that's been happening in Discord but UC now has a [Crowdin page](https://crowdin.com/project/ultracosmetics), and I'm working on figuring out how to integrate that with the GitHub repo.

**Comment by dennishzg** [comment]
thank you for telling me 👍
