### ISSUE TITLE
Back-To-Main-Menu-Custom-Command command

### ISSUE THREAD

**Issue by MrQuibe** [iSach/UltraCosmetics#61]
I use ChestCommands and
How to use Back-To-Main-Menu-Custom-Command command?
Sorry for my bad English. I'm brazilian.

**Comment by drewscool32** [comment]
same here

**Comment by Luuk5991** [comment]
Same here

**Comment by iSach** [comment]
Fixed in 2.1.3, just check your config there should be new fields at that place.
