### ISSUE TITLE
Pets are despawning directly after spawning

### ISSUE THREAD

**Issue by timothykra** [iSach/UltraCosmetics#615]
Tested versions: 1.19.4

Hi there. I am currently trying to get pets working on my server. I Load UltraCosmetics 2.8, Login as an OP with * permissions	Open the pet menu, and click on any pet and it does not work. 

Expected: The pet should spawn and follow me around until dismissed
Actual: The pet spawns, but instantly gets despawned.

Logs: https://pastebin.com/U41pP8te

I was referencing the issue below and checked if my world is included in the Enabled Worlds Config and I have the asterisk there which according to the comments means all worlds should be enabled yet it still does not work. 
https://github.com/iSach/UltraCosmetics/issues/108

**Comment by datatags** [comment]
UltraCosmetics 2.8 does not support 1.19.0, please use UC 2.7 or update your server version.

Also, this repository is no longer in use, please report any other issues to the new one: https://github.com/datatags/UltraCosmetics
