### ISSUE TITLE
Suggestion: '' for no message

### ISSUE THREAD

**Issue by DanSpedey** [iSach/UltraCosmetics#65]
Hello,

Could you please make it so if you make a message '', it disables it? (Unless there is another to disable a message which I do not know about, if so, could you tell me please.)

Thanks

**Comment by iSach** [comment]
I will add that.

**Comment by DanSpedey** [comment]
Thank you

**Comment by iSach** [comment]
Sorry for long delay, still planned. Will be added in 2.1.4/2.2 (depends on how I name it)
