### ISSUE TITLE
Could not pass event InventoryClickEvent

### ISSUE THREAD

**Issue by BlackBeltPanda** [iSach/UltraCosmetics#66]
Using UltraCosmetics 2.1 on Paper 1.9

Getting this error when players use the menus: http://pastebin.com/raw/Df610E17

**Comment by iSach** [comment]
Please use official Spigot.

**Comment by BlackBeltPanda** [comment]
Same problem in official Spigot 1.9. Seems to be an issue with the ammo purchase GUI; players are able to remove items from that GUI and clicking them does nothing.

**Comment by BlackBeltPanda** [comment]
Appears to be fixed in 2.1.1. =)

**Comment by iSach** [comment]
great
