### ISSUE TITLE
Can't Use Morphs/Pets/Treasure Chest!

### ISSUE THREAD

**Issue by TomKillerS** [iSach/UltraCosmetics#67]
Hello, @iSach i have problem with using Morphs/Pets/Treasure Chests, i have tried updating the LIBSDISGUISE/PROTOCOLLIB but, nothing happen my server was updated to 1.9 a month a ago, i am waiting for this plugin to be updated to 1.9
you can view the images here: 

EVERY THING IS VANISH: http://i.imgur.com/OOeXI2L.png
Chat shows that i spawned them but, they didn't appear!: http://i.imgur.com/pmz7NJh.png

please help.

**Comment by TomKillerS** [comment]
27.03 00:01:54 [Server] INFO [UltraCosmetics] Enabling UltraCosmetics v2.1
27.03 00:01:54 [Server] INFO UltraCosmetics -> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
27.03 00:01:54 [Server] INFO UltraCosmetics -> UltraCosmetics v2.1 is being loaded... (server: 1.9)
27.03 00:01:54 [Server] INFO UltraCosmetics -> 
27.03 00:01:54 [Server] INFO UltraCosmetics -> Thanks for having downloaded it!
27.03 00:01:54 [Server] INFO UltraCosmetics -> 
27.03 00:01:54 [Server] INFO UltraCosmetics -> Plugin by iSach.
27.03 00:01:54 [Server] INFO UltraCosmetics -> Link: http://bit.ly/UltraCosmetics
27.03 00:01:54 [Server] INFO UltraCosmetics -> 
27.03 00:01:54 [Server] INFO UltraCosmetics -> Loading configuration...
27.03 00:01:54 [Server] INFO UltraCosmetics -> Config file doesn't exist yet.
27.03 00:01:54 [Server] INFO UltraCosmetics -> Creating Config File and loading it.
27.03 00:01:54 [Server] INFO UltraCosmetics -> Configuration loaded.
27.03 00:01:54 [Server] INFO UltraCosmetics -> 
27.03 00:01:54 [Server] INFO UltraCosmetics -> Registering Custom Entities...
27.03 00:01:54 [Server] INFO UltraCosmetics -> Custom Entities registered.
27.03 00:01:54 [Server] INFO UltraCosmetics -> 
27.03 00:01:54 [Server] INFO UltraCosmetics -> 
27.03 00:01:54 [Server] INFO UltraCosmetics -> Preparing Metrics data.
27.03 00:01:54 [Server] INFO UltraCosmetics -> Data sent to Metrics successfully.
27.03 00:01:54 [Server] INFO UltraCosmetics -> 
27.03 00:01:54 [Server] INFO UltraCosmetics -> 
27.03 00:01:54 [Server] INFO UltraCosmetics -> NoteBlockAPI loaded and hooked.
27.03 00:01:54 [Server] INFO UltraCosmetics -> 
27.03 00:01:55 [Multicraft] Skipped 17 lines due to rate limit (30/s)
27.03 00:01:55 [Server] INFO UltraCosmetics -> Registering Cosmetics...
27.03 00:01:55 [Server] INFO UltraCosmetics -> Gadgets Registered.
27.03 00:01:55 [Server] INFO UltraCosmetics -> 
27.03 00:01:55 [Server] INFO UltraCosmetics -> Registering listeners...
27.03 00:01:55 [Server] INFO UltraCosmetics -> Listeners registered.
27.03 00:01:55 [Server] INFO UltraCosmetics -> 
27.03 00:01:55 [Server] INFO UltraCosmetics -> 
27.03 00:01:55 [Server] INFO UltraCosmetics -> UltraCosmetics successfully finished loading and is now enabled! (server: 1.9)
27.03 00:01:55 [Server] INFO UltraCosmetics -> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

**Comment by TomKillerS** [comment]
please someone help!

**Comment by iSach** [comment]
Trying to sell UltraCosmetics is bad.
