### ISSUE TITLE
Suggestion: Treasure Chest Stations

### ISSUE THREAD

**Issue by Yellowdash34** [iSach/UltraCosmetics#71]
Hello iSach! I have a suggestion for the plugin.

Treasure chests currently can be opened anywhere there is room, but that means they can block paths. Can you add a feature that teleports them to a certain location(s) to open chests?

Thanks!

**Comment by HyperClawz** [comment]
Yes add this

**Comment by iSach** [comment]
Treasure Command is there for that.

**Comment by HyperClawz** [comment]
How is this done?

**Comment by iSach** [comment]
/uc treasure <player> <x> <y> <z> <world>

**Comment by HyperClawz** [comment]
Sorry i ment how do I add this command to a chest using command signs like uc treasure %player% x y z world

**Comment by iSach** [comment]
@HyperClawz You can download a Command Signs plugin.
