### ISSUE TITLE
Quake gun salvageable (mcMMO)

### ISSUE THREAD

**Issue by saladfingers** [iSach/UltraCosmetics#76]
The Diamond Hoe can be repeatably salvaged using the mcMMO salvage ability. This potentially gives the player an unlimited diamond source.

Could the item be changed to a wooden hoe, or possibly add a configuration option for the menu items.

Thanks.

Edit: Configurable menu items would actually fix numerous problems I am having at the moment. I would be more than willing to download the source and rename the items myself - the trouble is I have no idea how to compile bukkit plugins. 

If it's easier for you to explain how I compile this plugin, or point me in the right direction, I will make the changes for myself :)

**Comment by saladfingers** [comment]
I have managed to compile this myself with the changes I needed. The plugin loads fine, I see a message saying that it is enabled for 1.9, however, it keeps trying to reference 1.8:

org/bukkit/craftbukkit/v1_8_R3/inventory/CraftInventory

Using my extremely limited knowledge, it appears as though the plugin does compile for both 1.8 and 1.9 (I have both server jars as dependencies in eclipse).

**Comment by iSach** [comment]
Hello, so, it's fixed? Sorry for the long delay.
