### ISSUE TITLE
Second hand issues 

### ISSUE THREAD

**Issue by scruffles87** [iSach/UltraCosmetics#77]
I'm not the best at explaining, but here goes. 
Normally, the plugin doesn't let you place/use the items that are spawned in as gadgets. But, if you put the gadget in your second hand, then switch it into your main hand again, you can place it. Since one of the gadgets is a beacon, a player could easily get infinite beacons.

**Comment by philip-ulrich** [comment]
This issue is still in existence. 

To reproduce:
Choose beacon gadget
Place in offhand
Disable all cosmetics
Place in hand
???
Profit

**Comment by iSach** [comment]
Fixed on 2.1.3
