### ISSUE TITLE
No permissions for cosmetics

### ISSUE THREAD

**Issue by CraftaPanda** [iSach/UltraCosmetics#79]
Hi, when someone tries to select a gadget they found in a treasure chest it says they have no permission. But when I give them the ultracosmetics.gadgets.* permission they are allowed to access all gadgets (I am having this problem with all of my cosmetics). My server version is Spigot 1.9.2

Please help me!

**Comment by iSach** [comment]
What permissions plugin? Please check Config, in Treasure Chests part, the permission command.

**Comment by CraftaPanda** [comment]
First of all thanks for answering so fast. I am using the groupmanager plugin and the command I put in is: manuaddp %name% %permission%. Manuaddp stands for:
- man = manager = groupmanager
- u = user
- add = add
- p = permission

I put it in the correct order so idk what is wrong. The players just dont get the permission to access the cosmetic

**Comment by iSach** [comment]
Sorry for the long delay of reply.
I don't know what's wrong with that, this should be good, please try Pex.
