### ISSUE TITLE
lag urgently!

### ISSUE THREAD

**Issue by FunnyCraft** [iSach/UltraCosmetics#82]
http://SSMaker.ru/69975e65/ - see!

**Comment by iSach** [comment]
0.6%, this isn't lag.

**Comment by FunnyCraft** [comment]
watch per tick.

**Comment by iSach** [comment]
0.78% of each tick, this is nothing, the amount doesn't matter.

**Comment by FunnyCraft** [comment]
No, it caused a lag.

**Comment by FunnyCraft** [comment]
I'm still waiting for correction.

**Comment by iSach** [comment]
I told you it was just taking 0.6% of each tick, this isn't the source of a server lag.
If you're having a client side lag, it's your computer not the plugin.

**Comment by JHXSMatthew** [comment]
:)
Those particle packets won't lag your server.

**Comment by FunnyCraft** [comment]
At 200 online with your plugin tps 14-17
without 20 tps.

**Comment by iSach** [comment]
Third time I repeat it, this timing is clearly not makign server lag, send your whole timings report
