### ISSUE TITLE
New Players Can Use Anything They Want, The only Way im able to stop them from using that Morph or Mount is to take away there permission

### ISSUE THREAD

**Issue by MrXDubstepRemix** [iSach/UltraCosmetics#84]
When I installed this plugin I noticed that everyone had Morphs, pets, mounts, etc. I looked through the  config and found Nothing, I dont know if I missed something but I would like players to find the Mounts, morphs, etc. Say if im new to my server and see cosmetics I might want too see what kind of cosmetics there are. If I find one I like than I might want to "try" and use it. Ill click the Mount and realize it spawned. By that time I may have realized that I didn't unlock it. If anyone has any advice it would be very helpful!

**Comment by SmokingTrooper** [comment]
Do you give your default group/rank all of the ultracosmetics permissions?

**Comment by iSach** [comment]
1 week of inactivity from @MrXDubstepRemix, closed.
