### ISSUE TITLE
Pets don`t teleport with players on world change.

### ISSUE THREAD

**Issue by Joopie123** [iSach/UltraCosmetics#86]
Hello,

I use your plugin for a long time, and it``s great! But now i``ve found a bug. When players have a pet, and they teleport a another world, the pet is not getting with them. They just stand in the world they spawned. Do you have a solution for this? Or is it just a config problem?

**Comment by mikey1665** [comment]
Might be a code problem.

**Comment by Joopie123** [comment]
Can you repair it?

**Comment by iSach** [comment]
I still can't determine what exactly creates the bug, not able to fix it. :/
