### ISSUE TITLE
error - INVENTORY_OPEN

### ISSUE THREAD

**Issue by mat41997** [iSach/UltraCosmetics#88]
logs
http://hastebin.com/etiyozicaz.avrasm

**Comment by SmokingTrooper** [comment]
it probably has something to do with nocheatplus. Try to disable it in your hub world (or the world with the cosmetics) using a per world plugin-plugin. PerWorldPlugins is a good one. After that I think it shouldnt happen anymore

**Comment by iSach** [comment]
Indeed coming from NCP.
