### ISSUE TITLE
Morphs won't work but i Installed Lib's Disguises & Protocollib

### ISSUE THREAD

**Issue by Quadri1337** [iSach/UltraCosmetics#90]
I installed Lib's Disguises and Protocollib but the Morphs won't work.

Help Pls

Quadri1337

**Comment by MrXDubstepRemix** [comment]
Do you have IDisguise Installed? That might be the problem why

**Comment by SmokingTrooper** [comment]
Have you enabled morphs in the config?

**Comment by iSach** [comment]
One week of inactivity from @Quadri1337, closing.
