### ISSUE TITLE
Custom command when leaving GUI

### ISSUE THREAD

**Issue by Luuk5991** [iSach/UltraCosmetics#92]
How can I add a custom command for the home button?,
When I add a command in the config this doesn't work.
How can I fix this?

**Comment by SmokingTrooper** [comment]
what is the command if I may ask?

**Comment by SmokingTrooper** [comment]
and how did you put it in the config?

**Comment by Luuk5991** [comment]
`  Close-GUI-After-Select: true
  Back-To-Main-Menu-Custom-Command: 'Cosmetics'

Like this

**Comment by SmokingTrooper** [comment]
if the command is cosmeticsgui you should also put that in the config.
It should look like this:

Close-GUI-After-Select: true
Back-To-Main-Menu-Custom-Command: 'CosmeticsGUI'

**Comment by iSach** [comment]
Fixed in 2.1.3
