### ISSUE TITLE
C418 - Ward

### ISSUE THREAD

**Issue by aj4sure125** [iSach/UltraCosmetics#93]
Hi.

So I've been having an issue with UltraCosmetics lately. 

You know the clicking sound the plugin makes when either: A gadget has finished reloading or, the explosive sheep is about to explode?

Yea, for some reason, the clicking sound is replaced with C418 - WARD in High Pitched. It seems to keep playing and it doesn't stop until I quit the server. The version is the latest, 2.1.2. I've restarted the server, I've reinstalled the plugin and folder. I did everything and it just won't stop playing that song. Any idea on how to fix this? Thanks.

**Comment by iSach** [comment]
Hey!

Already experienced by another user, update Spigot, it's just a Spigot problem. :)
