### ISSUE TITLE
Error - Morphs - PaperSpigot 1.9.4

### ISSUE THREAD

**Issue by mat41997** [iSach/UltraCosmetics#97]
timings
https://timings.aikar.co/v2/?id=2e561b9cf1ec4140b0c5920272308862

logs
http://hastebin.com/digozejeto.avrasm

**Comment by iSach** [comment]
Update Lib's Disguises

**Comment by mat41997** [comment]
ok, it works. THX : ))

**Comment by iSach** [comment]
What is your version of Libs' Disguises now?
The error says it can't find a method of Lib's Disguises.

**Comment by mat41997** [comment]
name: LibsDisguises
main: me.libraryaddict.disguise.LibsDisguises
description: A disguise plugin with various disguises.
version: 9.0.5
author: libraryaddict
authors: [Byteflux, Navid K.]
softdepend: [ProtocolLib]

click the blue download button on this site
https://www.spigotmc.org/resources/protocollib.1997/
to download my version ProtocolLib plugin

**Comment by iSach** [comment]
This is weird, I don't know why it generates that error. I just decompiled Lib's Disguises and the method is there.

**Comment by mat41997** [comment]
my LibsDisguises config
http://hastebin.com/qatigaboqi.vbs

**Comment by mat41997** [comment]
and new mounts error
http://hastebin.com/ruqupezuza.avrasm

**Comment by mat41997** [comment]
and new gadgets error
http://hastebin.com/amatedexod.avrasm

**Comment by FunnyCraft** [comment]
Libsdisguises updated reception method, see you probably are using the old method

**Comment by iSach** [comment]
errors seem to come from NCP or something like that cancelling velocities.

@FunnyCraft error says the bounding box method doesn't exist, when testing morphs in 1.9.4 with last Lib's disguises and corresponding ProtocolLib, it's working.

**Comment by DeltaEvolution** [comment]
For the velocity it's a warning of PaperSpigot [https://hub.spigotmc.org/stash/projects/PAPER/repos/paperspigot/browse/Spigot-Server-Patches/0098-Add-velocity-warnings.patch](patch) , I thinks this behavior could be disabled in configuration
