### ISSUE TITLE
config.yml spammed with "# List of the enabled categories."

### ISSUE THREAD

**Issue by Mrtenz** [iSach/UltraCosmetics#98]
I tried to boot my server with 2.1.3, but UltraCosmetics was stuck at "Loading config." I checked the config and it contains about 262.145 lines with "# List of the enabled categories."

**Comment by iSach** [comment]
What Server Jar are you using?
Add this before the lines (after having deleted those lines)

```
# If set to true, will check for updates
Check-For-Updates: true
```

**Comment by Mrtenz** [comment]
I'm using Spigot 1.9.2. "Check-For-Updates: true" is in the config, but the lines keep coming back.

**Comment by iSach** [comment]
They come between that and the "Categories-Enabled:"?

**Comment by Mrtenz** [comment]
No, they are on the top of the file.

**Comment by iSach** [comment]
They should not, I don't really know why it happens. Did you try to reset config?

**Comment by Mrtenz** [comment]
I deleted the config and started the server. After a while they came back.

**Comment by Mrtenz** [comment]
This keeps happening, but ~65.000 lines with "# - Do you want a BackToMainMenu Arrow in it?"

I really like the plugin, but I cant use it if my config keeps getting spammed and prevents the server from booting.

**Comment by iSach** [comment]
Did you delete any comment lines before it happened?

**Comment by Mrtenz** [comment]
I deleted all the lines at the top.

**Comment by iSach** [comment]
You shouldn't do that.

**Comment by iSach** [comment]
That's the cause

**Comment by Mrtenz** [comment]
Well, can you fix it?

**Comment by iSach** [comment]
Just don't delete lines, and it won't bug.

**Comment by Mrtenz** [comment]
If I don't delete the 50.000 or more lines the plugin simply won't load and block the whole server from loading...
