### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by FunnyCraft** [iSach/UltraCosmetics#99]
http://pastebin.com/C8VxAbnA

**Comment by FunnyCraft** [comment]
http://pastebin.com/R2TUtBjq

**Comment by Dimatert9** [comment]
http://pastebin.com/UbUU9C8i
http://pastebin.com/Bw0cXjhV - latest libsdisguise
http://pastebin.com/cEDaT1Tg

**Comment by iSach** [comment]
Please reopen an issue if still not fixed in 2.3.1
